---
permalink: sg6000/optional-changing-raid-mode-sg6000-only.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, raid, raid mode, change, changing, modify, DDP, ddp16, raid6 
summary: 'È possibile passare a una modalità RAID diversa sull"appliance per soddisfare i requisiti di storage e ripristino. È possibile modificare la modalità solo prima di implementare il nodo di storage dell"appliance.' 
---
= Opzionale: Modifica della modalità RAID (solo SG6000)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile passare a una modalità RAID diversa sull'appliance per soddisfare i requisiti di storage e ripristino. È possibile modificare la modalità solo prima di implementare il nodo di storage dell'appliance.

.Di cosa hai bisogno
* Si sta utilizzando qualsiasi client in grado di connettersi a StorageGRID.
* Il client dispone di un xref:../admin/web-browser-requirements.adoc[browser web supportato].


.A proposito di questa attività
Prima di implementare l'appliance come nodo di storage, è possibile scegliere una delle seguenti opzioni di configurazione del volume:

* *DDP*: Questa modalità utilizza due unità di parità ogni otto unità dati. Questa è la modalità predefinita e consigliata per tutti gli appliance. Rispetto a RAID6, DDP offre migliori prestazioni di sistema, tempi di ricostruzione ridotti dopo guasti al disco e facilità di gestione.
+

IMPORTANT: DDP non fornisce la protezione contro la perdita di cassetto nelle appliance SG6060 a causa dei due SSD. La protezione dalle perdite dei cassetti è efficace in tutti gli shelf di espansione aggiunti a un SG6060.

* *DDP16*: Questa modalità utilizza due unità di parità ogni 16 unità dati, il che comporta una maggiore efficienza dello storage rispetto al DDP. Rispetto a RAID6, il sistema DDP16 offre migliori performance di sistema, tempi di ricostruzione ridotti dopo guasti del disco, facilità di gestione ed efficienza dello storage paragonabile. Per utilizzare la modalità DDP16, la configurazione deve contenere almeno 20 dischi. Il DDP16 non fornisce la protezione contro le perdite di cassetto.
* *RAID6*: Questa modalità utilizza due unità di parità per ogni 16 o più unità dati. Per utilizzare la modalità RAID 6, la configurazione deve contenere almeno 20 dischi. Sebbene RAID6 possa aumentare l'efficienza dello storage dell'appliance rispetto a DDP, non è consigliato per la maggior parte degli ambienti StorageGRID.



IMPORTANT: Se alcuni volumi sono già stati configurati o se StorageGRID è stato installato in precedenza, la modifica della modalità RAID comporta la rimozione e la sostituzione dei volumi. Tutti i dati presenti su tali volumi andranno persi.

.Fasi
. Aprire un browser e inserire uno degli indirizzi IP del controller di elaborazione dell'appliance.
+
`*https://_Controller_IP_:8443*`

+
`_Controller_IP_` È l'indirizzo IP del controller di calcolo (non dello storage controller) su una qualsiasi delle tre reti StorageGRID.

+
Viene visualizzata la pagina iniziale del programma di installazione dell'appliance StorageGRID.

. Selezionare *Advanced* (Avanzate) > *RAID Mode* (modalità RAID).
. Nella pagina *Configure RAID Mode* (Configura modalità RAID), selezionare la modalità RAID desiderata dall'elenco a discesa Mode (modalità).
. Fare clic su *Save* (Salva).


.Informazioni correlate
http://mysupport.netapp.com/info/web/ECMP1658252.html["Sito di documentazione dei sistemi NetApp e-Series"^]
