---
permalink: sg6000/preparing-site-sg6000.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, install, installation, site prep, site preparating, preparing site, site requirements, requirements, site, dimensions, weight, weights, temperature, humidity, altitude, airflow, heat, wiring, power, grounding, facility 
summary: 'Prima di installare l"apparecchio, assicurarsi che il sito e l"armadietto o il rack che si intende utilizzare soddisfino le specifiche di un"appliance StorageGRID.' 
---
= Preparazione del sito (SG6000)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di installare l'apparecchio, assicurarsi che il sito e l'armadietto o il rack che si intende utilizzare soddisfino le specifiche di un'appliance StorageGRID.

.Fasi
. Verificare che il sito soddisfi i requisiti di temperatura, umidità, intervallo di altitudine, flusso d'aria, dissipazione del calore, cablaggio, alimentazione e messa a terra. Per ulteriori informazioni, consulta il NetApp Hardware Universe.
. Verificare che la propria sede fornisca alimentazione CA a 240 volt per SG6060 o a 120 volt per SGF6024.
. Procurarsi un cabinet da 19" (48.3 cm) o un rack per gli scaffali di queste dimensioni (senza cavi):
+
|===
| Tipo di shelf | Altezza | Larghezza | Profondità | Peso massimo 


 a| 
*Shelf di controller E2860* per SG6060
 a| 
6.87 poll.

(17.46 cm)
 a| 
17.66 poll.

(44.86 cm)
 a| 
38.25 poll.

(97.16 cm)
 a| 
250 libbre

(113 kg)



 a| 
*Shelf di espansione opzionale* per SG6060 (uno o due)
 a| 
6.87 poll.

(17.46 cm)
 a| 
17.66 poll.

(44.86 cm)
 a| 
38.25 poll.

(97.16 cm)
 a| 
250 libbre

(113 kg)



 a| 
*Shelf di controller EF570* per SGF6024
 a| 
3.35 poll.

(8.50 cm)
 a| 
17.66 poll.

(44.86 cm)
 a| 
19.00 poll.

(48.26 cm)
 a| 
51.74 libbre

(23.47 kg)



 a| 
*Controller SG6000-CN* per ogni appliance
 a| 
1.70 poll.

(4.32 cm)
 a| 
17.32 poll.

(44.0 cm)
 a| 
32.0 poll.

(81.3 cm)
 a| 
39 libbre

(17.7 kg)

|===
. Decidere dove installare l'appliance.
+

CAUTION: Quando si installa lo shelf del controller E2860 o gli shelf di espansione opzionali, installare l'hardware dal basso verso la parte superiore del rack o dell'armadio per evitare che l'apparecchiatura si ribalti. Per assicurarsi che l'apparecchiatura più pesante si trovi nella parte inferiore del cabinet o del rack, installare il controller SG6000-CN sopra lo shelf del controller E2860 e gli shelf di espansione.

+

IMPORTANT: Prima di eseguire l'installazione, verificare che i cavi ottici da 0,5 m forniti con l'apparecchio o i cavi forniti siano sufficientemente lunghi per il layout pianificato.



.Informazioni correlate
https://hwu.netapp.com["NetApp Hardware Universe"^]

https://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità NetApp"^]
