---
permalink: sg6000/upgrading-santricity-os-on-storage-controllers.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, controller, storage controller, upgrade, upgrading, SANtricity OS, SANtricity 
summary: 'Per garantire un funzionamento ottimale dello storage controller, è necessario eseguire l"aggiornamento alla versione di manutenzione più recente del sistema operativo SANtricity che sia qualificato per l"appliance StorageGRID. Consulta il tool della matrice di interoperabilità NetApp (IMT) per determinare la versione da utilizzare. Se hai bisogno di assistenza, contatta il supporto tecnico.' 
---
= Aggiornare il sistema operativo SANtricity sui controller di storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per garantire un funzionamento ottimale dello storage controller, è necessario eseguire l'aggiornamento alla versione di manutenzione più recente del sistema operativo SANtricity che sia qualificato per l'appliance StorageGRID. Consulta il tool per la matrice di interoperabilità NetApp (IMT) per determinare la versione da utilizzare. Se hai bisogno di assistenza, contatta il supporto tecnico.

Utilizzare una delle seguenti procedure in base alla versione di SANtricity OS attualmente installata:

* Se lo storage controller utilizza SANtricity OS 08.42.20.00 (11.42) o versione successiva, utilizzare Grid Manager per eseguire l'aggiornamento.
+
xref:upgrading-santricity-os-on-storage-controllers-using-grid-manager-sg6000.adoc[Aggiorna il sistema operativo SANtricity sui controller di storage utilizzando Grid Manager]

* Se lo storage controller utilizza una versione di SANtricity OS precedente alla 08.42.20.00 (11.42), utilizzare la modalità di manutenzione per eseguire l'aggiornamento.
+
xref:upgrading-santricity-os-on-storage-controllers-using-maintenance-mode-sg6000.adoc[Aggiornare il sistema operativo SANtricity sui controller di storage utilizzando la modalità di manutenzione]




IMPORTANT: Quando si aggiorna il sistema operativo SANtricity per l'appliance di storage, è necessario seguire le istruzioni nella documentazione di StorageGRID. Se si utilizzano altre istruzioni, l'apparecchio potrebbe diventare inutilizzabile.

.Informazioni correlate
https://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità NetApp"^]

https://mysupport.netapp.com/site/products/all/details/storagegrid-appliance/downloads-tab["Download NetApp: Appliance StorageGRID"^]

xref:../monitor/index.adoc[Monitorare e risolvere i problemi]
