---
permalink: audit/client-write-audit-messages.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, messages, client write, OVWR, SDEL, SPOS, SPUT, SUPD, WDEL, WPUT, S3, swift 
summary: 'I messaggi di audit di scrittura del client vengono registrati quando un"applicazione client S3 o Swift richiede di creare o modificare un oggetto.' 
---
= Messaggi di audit di scrittura del client
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I messaggi di audit di scrittura del client vengono registrati quando un'applicazione client S3 o Swift richiede di creare o modificare un oggetto.

|===
| Codice | Descrizione | Utilizzato da | Vedere 


 a| 
OVWR
 a| 
Object Overwrite: Registra una transazione per sovrascrivere un oggetto con un altro oggetto.
 a| 
Client S3

Client Swift
 a| 
xref:ovwr-object-overwrite.adoc[OVWR: Sovrascrittura degli oggetti]



 a| 
SDEL
 a| 
S3 DELETE (ELIMINA S3): Registra una transazione riuscita per eliminare un oggetto o un bucket.

*Nota:* se la transazione opera su una sottorisorsa, il messaggio di audit includerà il campo S3SR.
 a| 
Client S3
 a| 
xref:sdel-s3-delete.adoc[SDEL: ELIMINAZIONE S3]



 a| 
SPOS
 a| 
S3 POST: Registra una transazione riuscita per ripristinare un oggetto dallo storage AWS Glacier a un Cloud Storage Pool.
 a| 
Client S3
 a| 
xref:spos-s3-post.adoc[SPOS: POST S3]



 a| 
SPUT
 a| 
S3 PUT: Registra una transazione riuscita per creare un nuovo oggetto o bucket.

*Nota:* se la transazione opera su una sottorisorsa, il messaggio di audit includerà il campo S3SR.
 a| 
Client S3
 a| 
xref:sput-s3-put.adoc[SPUT: S3 PUT]



 a| 
SUPD
 a| 
S3 Metadata Updated: Registra una transazione riuscita per aggiornare i metadati di un oggetto o bucket esistente.
 a| 
Client S3
 a| 
xref:supd-s3-metadata-updated.adoc[SUPD: Metadati S3 aggiornati]



 a| 
WDEL
 a| 
Eliminazione rapida: Registra una transazione riuscita per eliminare un oggetto o un container.
 a| 
Client Swift
 a| 
xref:wdel-swift-delete.adoc[WDEL: ELIMINAZIONE rapida]



 a| 
WPUT
 a| 
Swift PUT: Registra una transazione riuscita per creare un nuovo oggetto o container.
 a| 
Client Swift
 a| 
xref:wput-swift-put.adoc[WPUT: MESSA rapida]

|===