---
permalink: audit/object-delete-transactions.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, messages, transaction, transactions, Object delete, S3 delete, Swift delete, S3, Swift, SDEL, WDEL 
summary: 'È possibile identificare le transazioni di eliminazione degli oggetti nel registro di audit individuando i messaggi di audit specifici dell"API (S3 e Swift).' 
---
= Transazioni di eliminazione degli oggetti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile identificare le transazioni di eliminazione degli oggetti nel registro di audit individuando i messaggi di audit specifici dell'API (S3 e Swift).

Non tutti i messaggi di audit generati durante una transazione di eliminazione sono elencati nelle tabelle seguenti. Sono inclusi solo i messaggi necessari per tracciare la transazione di eliminazione.



== S3 eliminare i messaggi di audit

|===
| Codice | Nome | Descrizione | Traccia | Vedere 


 a| 
SDEL
 a| 
S3 Elimina
 a| 
Richiesta di eliminazione dell'oggetto da un bucket.
 a| 
CBID, S3KY
 a| 
xref:sdel-s3-delete.adoc[SDEL: ELIMINAZIONE S3]

|===


== Eliminazione rapida dei messaggi di audit

|===
| Codice | Nome | Descrizione | Traccia | Vedere 


 a| 
WDEL
 a| 
Eliminazione rapida
 a| 
Richiesta di eliminazione dell'oggetto da un container o dal container.
 a| 
CBID, WOBJ
 a| 
xref:wdel-swift-delete.adoc[WDEL: ELIMINAZIONE rapida]

|===