---
permalink: audit/object-storage-audit-messages.html 
sidebar: sidebar 
keywords: storagegrid, audit, object storage, object management, object retrieval, node transfer, verification, APCT, ARCB, ARCE, ARCT, AREM, ASCE, ASCT, ATCE, AVCC, CBSE, CBRE, SCMT, SREM 
summary: 'Si consiglia di acquisire familiarità con i messaggi di audit appartenenti alla categoria di audit dello storage a oggetti. Si tratta di eventi correlati allo storage e alla gestione di oggetti all"interno del sistema StorageGRID. Tra cui storage a oggetti e recuperi, trasferimenti da grid-node a grid-node e verifiche.' 
---
= Messaggi di audit dello storage a oggetti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si consiglia di acquisire familiarità con i messaggi di audit appartenenti alla categoria di audit dello storage a oggetti. Si tratta di eventi correlati allo storage e alla gestione di oggetti all'interno del sistema StorageGRID. Tra cui storage a oggetti e recuperi, trasferimenti da grid-node a grid-node e verifiche.

|===
| Codice | Descrizione | Vedere 


 a| 
APCT
 a| 
Eliminazione dell'archivio dal livello cloud: I dati degli oggetti archiviati vengono cancellati da un sistema storage di archiviazione esterno, che si connette a StorageGRID tramite l'API S3.
 a| 
xref:apct-archive-purge-from-cloud-tier.adoc[APCT: Eliminazione dell'archivio dal Cloud-Tier]



 a| 
ARCB
 a| 
Archive Object Retrieve Begin (inizio recupero oggetto archivio): Il servizio ARC avvia il recupero dei dati oggetto dal sistema di storage di archiviazione esterno.
 a| 
xref:arcb-archive-object-retrieve-begin.adoc[ARCB: Inizio recupero oggetto archivio]



 a| 
ARCE
 a| 
Archive Object Retrieve End (fine recupero oggetto archivio): I dati dell'oggetto sono stati recuperati da un sistema di storage di archiviazione esterno e il servizio ARC segnala lo stato dell'operazione di recupero.
 a| 
xref:arce-archive-object-retrieve-end.adoc[ARCE: Fine recupero oggetto archivio]



 a| 
ARCT
 a| 
Recupero archivio dal livello cloud: I dati degli oggetti archiviati vengono recuperati da un sistema storage di archiviazione esterno, che si connette a StorageGRID tramite l'API S3.
 a| 
xref:arct-archive-retrieve-from-cloud-tier.adoc[ARCT: Recupero archivio da Cloud-Tier]



 a| 
AREM
 a| 
Archive Object Remove (Rimozione oggetto archivio): Un blocco di contenuto è stato eliminato correttamente o senza successo dal sistema di storage di archiviazione esterno.
 a| 
xref:arem-archive-object-remove.adoc[AREM: Rimozione dell'oggetto di archiviazione]



 a| 
ASCE
 a| 
Archive Object Store End (fine archivio oggetti): Un blocco di contenuto è stato scritto nel sistema di storage di archiviazione esterno e il servizio ARC segnala lo stato dell'operazione di scrittura.
 a| 
xref:asce-archive-object-store-end.adoc[ASCE: Fine archivio oggetti]



 a| 
ASTT
 a| 
Livello cloud archivio: I dati degli oggetti vengono memorizzati in un sistema storage di archiviazione esterno, che si connette a StorageGRID tramite l'API S3.
 a| 
xref:asct-archive-store-cloud-tier.adoc[ASCT: Archivio Store Cloud-Tier]



 a| 
ATCE
 a| 
Archive Object Store Begin (inizio archivio: Scrittura di un blocco di contenuto in uno storage di archiviazione esterno).
 a| 
xref:atce-archive-object-store-begin.adoc[ATCE: Inizio archivio oggetti]



 a| 
AVCC
 a| 
Archive Validate Cloud-Tier Configuration (convalida archivio configurazione livello cloud): Le impostazioni dell'account e del bucket fornite sono state validate correttamente o senza successo.
 a| 
xref:avcc-archive-validate-cloud-tier-configuration.adoc[AVCC: Convalida archivio configurazione Cloud-Tier]



 a| 
CBSE
 a| 
Object Send End (fine invio oggetto): L'entità di origine ha completato un'operazione di trasferimento dei dati dal nodo griglia al nodo griglia.
 a| 
xref:cbse-object-send-end.adoc[CBSE: Fine invio oggetto]



 a| 
CBRE
 a| 
Object Receive End (fine ricezione oggetto): L'entità di destinazione ha completato un'operazione di trasferimento dei dati dal nodo griglia al nodo griglia.
 a| 
xref:cbre-object-receive-end.adoc[CBRE: Fine ricezione oggetto]



 a| 
SCMT
 a| 
Commit dell'archivio oggetti: Un blocco di contenuto è stato completamente memorizzato e verificato e può essere richiesto.
 a| 
xref:scmt-object-store-commit.adoc[SCMT: Commit dell'archivio di oggetti]



 a| 
SREM
 a| 
Rimozione archivio oggetti: Un blocco di contenuto è stato cancellato da un nodo griglia e non può più essere richiesto direttamente.
 a| 
xref:srem-object-store-remove.adoc[SREM: Rimozione dell'archivio di oggetti]

|===