---
settings:
  name: StorageGRID
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
    lipi_enabled: false
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: StorageGRID 11.6 documenti
    url: "/index.html"
  - section: release-notes
  - title: Inizia subito
    entries:
    - section: primer
    - section: network
  - title: Installazione e manutenzione dell'hardware dell'appliance
    entries:
    - section: sg100-1000
    - section: sg6000
    - section: sg5700
    - section: sg5600
  - title: Installare e aggiornare il software
    entries:
    - section: upgrade
    - section: rhel
    - section: ubuntu
    - section: vmware
  - title: Eseguire l'amministrazione del sistema
    entries:
    - section: admin
    - section: ilm
    - section: harden
    - section: fabricpool
  - title: USA StorageGRID
    entries:
    - section: tenant
    - section: s3
    - section: swift
  - title: Monitorare e gestire StorageGRID
    entries:
    - section: monitor
    - section: expand
    - section: maintain
    - section: audit
  - title: Abilitare StorageGRID
    url: "/storagegrid-enable.html"
  - title: Altre versioni
    url: "/earlier-versions.html"
  - title: Note legali
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Inizia subito
    links:
    - title: Note di rilascio
      url: "/release-notes/index.html"
    - title: Novità
      url: "/upgrade/whats-new.html"
    - title: Primer griglia
      url: "/primer/index.html"
    - title: Linee guida per la rete
      url: "/network/index.html"
  - title: Installare l'hardware di manutenzione
    links:
    - title: Appliance di servizi SG100 e SG1000
      url: "/sg100-1000/index.html"
    - title: Appliance di storage SG6000
      url: "/sg6000/index.html"
    - title: Appliance di storage SG5700
      url: "/sg5700/index.html"
    - title: Appliance di storage SG5600
      url: "/sg5600/index.html"
  - title: Installare il software di aggiornamento
    links:
    - title: Installare Red Hat Enterprise Linux o CentOS
      url: "/rhel/index.html"
    - title: Installare Ubuntu o Debian
      url: "/ubuntu/index.html"
    - title: Installare VMware
      url: "/vmware/index.html"
    - title: Aggiornare il software
      url: "/upgrade/index.html"
  - title: Configurare la griglia
    links:
    - title: Amministrare StorageGRID
      url: "/admin/index.html"
    - title: Gestire gli oggetti con ILM
      url: "/ilm/index.html"
    - title: Protezione avanzata del sistema
      url: "/harden/index.html"
    - title: Configurare StorageGRID per FabricPool
      url: "/fabricpool/index.html"
  - title: Gestire gli oggetti
    links:
    - title: Utilizzare un account tenant
      url: "/tenant/index.html"
    - title: Utilizzare S3
      url: "/s3/index.html"
    - title: USA Swift
      url: "/swift/index.html"
  - title: Manutenzione del monitor
    links:
    - title: Risoluzione dei problemi del monitor
      url: "/monitor/index.html"
    - title: Espandi il tuo grid
      url: "/expand/index.html"
    - title: Ripristinare la manutenzione
      url: "/maintain/index.html"
    - title: Esaminare i registri di audit
      url: "/audit/index.html"
  - title: Tutorial sulle demo
    links:
    - title: Scopri come attivare StorageGRID
      url: https://docs.netapp.com/us-en/storagegrid-enable/index.html
    - title: Videoteca StorageGRID
      url: https://www.youtube.com/playlist?list=PLdXI3bZJEw7nh2wGRA65iulXhtXwLiqrY
    - title: Servizi di apprendimento NetApp
      url: https://www.netapp.com/support-and-training/netapp-university/
  - title: Più risorse
    links:
    - title: Pagina di supporto di StorageGRID
      url: https://mysupport.netapp.com/site/products/all/details/5d9f1107e01d9c0001ee50f6/downloads-tab
    - title: Tool di matrice di interoperabilità NetApp (IMT)
      url: https://mysupport.netapp.com/matrix
    - title: Knowledge base di StorageGRID
      url: https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID
    - title: Blog di NetApp
      url: https://netapp.com/blog/
    - title: Community di NetApp
      url: https://community.netapp.com/
  - title: Altre versioni
    links:
    - title: Documentazione di StorageGRID 11.7
      url: https://docs.netapp.com/us-en/storagegrid-117/index.html
    - title: Documentazione di StorageGRID 11.5
      url: https://docs.netapp.com/us-en/storagegrid-115/index.html
    - title: Documentazione di StorageGRID 11.4
      url: https://docs.netapp.com/sgws-114/index.jsp
    - title: Documentazione di StorageGRID 11.3
      url: https://docs.netapp.com/sgws-113/index.jsp
    - title: Documentazione di StorageGRID 11.2
      url: https://docs.netapp.com/sgws-112/index.jsp
