---
settings:
  name: StorageGRID
  search: storagegrid-enable,storagegrid-116
  downlevel: true
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
    lipi_enabled: false
  versions:
  - version-number: '11.6'
    url: "/storagegrid-116"
  - version-number: '11.9'
    url: "/storagegrid"
  - version-number: '11.8'
    url: "/storagegrid-118"
  - version-number: '11.7'
    url: "/storagegrid-117"
  - version-number: '11.5'
    url: "/storagegrid-115"
  langs: it-it,us-en,de-de,es-es,fr-fr,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentazione di StorageGRID 11,6
    url: "/index.html"
  - title: Note di rilascio
    url: "/release-notes/index.html"
  - title: Inizia subito
    entries:
    - section: primer
    - section: network
  - title: Installazione e manutenzione dell'hardware dell'appliance
    entries:
    - section: sg100-1000
    - section: sg6000
    - section: sg5700
    - section: sg5600
  - title: Installare e aggiornare il software
    entries:
    - section: upgrade
    - section: rhel
    - section: ubuntu
    - section: vmware
  - title: Eseguire l'amministrazione del sistema
    entries:
    - section: admin
    - section: ilm
    - section: harden
    - section: fabricpool
  - title: USA StorageGRID
    entries:
    - section: tenant
    - section: s3
    - section: swift
  - title: Monitorare e gestire StorageGRID
    entries:
    - section: monitor
    - section: expand
    - section: maintain
    - section: audit
  - title: Abilitare StorageGRID
    url: "/storagegrid-enable.html"
  - title: Note legali
    url: "/legal-notices.html"
product-family:
  name: StorageGRID documentation
  repo: storagegrid-family
