---
permalink: upgrade/changes-to-tenant-management-api.html 
sidebar: sidebar 
keywords: tenant management api, api, api version, swagger, rest api 
summary: 'StorageGRID 11.6 utilizza la versione 3 dell"API di gestione dei tenant. La versione 3 è obsoleta della versione 2; tuttavia, la versione 1 e la versione 2 sono ancora supportate.' 
---
= Modifiche all'API di gestione del tenant
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 11.6 utilizza la versione 3 dell'API di gestione dei tenant. La versione 3 è obsoleta della versione 2; tuttavia, la versione 1 e la versione 2 sono ancora supportate.


IMPORTANT: È possibile continuare a utilizzare la versione 1 e la versione 2 dell'API di gestione con StorageGRID 11.6; tuttavia, il supporto per queste versioni dell'API verrà rimosso in una release futura di StorageGRID. Dopo l'aggiornamento a StorageGRID 11.6, le API v1 e v2 obsolete possono essere disattivate utilizzando `PUT /grid/config/management` API.

Per ulteriori informazioni, visitare il sito Web all'indirizzo xref:../tenant/understanding-tenant-management-api.adoc[Comprendere l'API di gestione dei tenant].



== Metodo PATCH obsoleto

Il metodo DI PATCH è stato obsoleto e verrà rimosso in una release futura. Se necessario, eseguire un'operazione PUT per sostituire una risorsa invece di utilizzare un'operazione DI PATCH per modificare la risorsa.
