---
permalink: upgrade/checking-systems-condition-before-upgrading-software.html 
sidebar: sidebar 
keywords: upgrade, grid tasks, firewall, ports 
summary: 'Prima di aggiornare un sistema StorageGRID, è necessario verificare che il sistema sia pronto per l"aggiornamento. È necessario assicurarsi che il sistema funzioni correttamente e che tutti i nodi della griglia siano operativi.' 
---
= Controllare le condizioni del sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di aggiornare un sistema StorageGRID, è necessario verificare che il sistema sia pronto per l'aggiornamento. È necessario assicurarsi che il sistema funzioni correttamente e che tutti i nodi della griglia siano operativi.

.Fasi
. Accedere a Grid Manager utilizzando un xref:../admin/web-browser-requirements.adoc[browser web supportato].
. Verificare la presenza di eventuali avvisi attivi e risolverli.
+
Per informazioni su avvisi specifici, consultare xref:../monitor/alerts-reference.adoc[Riferimenti agli avvisi].

. Verificare che non vi siano attività della griglia in conflitto attive o in sospeso.
+
.. Selezionare *SUPPORT* > *Tools* > *Grid topology*.
.. Selezionare *_Site_* > *_Primary Admin Node_* > *CMN* > *Grid Tasks* > *Configuration*.
+
I task ILME (Information Lifecycle Management Evaluation) sono gli unici task grid che possono essere eseguiti contemporaneamente all'aggiornamento del software.

.. Se altre attività della griglia sono attive o in sospeso, attendere il completamento o rilasciare il blocco.
+

NOTE: Contattare il supporto tecnico se un'attività non termina o non rilascia il blocco.



. Fare riferimento a. xref:../network/internal-grid-node-communications.adoc[Comunicazioni interne al nodo di rete] e. xref:../network/external-communications.adoc[Comunicazioni esterne] Assicurarsi che tutte le porte richieste per StorageGRID 11.6 siano aperte prima di eseguire l'aggiornamento.
+

IMPORTANT: Se sono state aperte porte firewall personalizzate, viene inviata una notifica durante la verifica preliminare dell'aggiornamento. È necessario contattare il supporto tecnico prima di procedere con l'aggiornamento.


