---
permalink: upgrade/estimating-time-to-complete-upgrade.html 
sidebar: sidebar 
keywords: upgrade, time estimate, duration, cassandra upgrade 
summary: 'Quando si pianifica un aggiornamento a StorageGRID 11.6, è necessario prendere in considerazione quando eseguire l"aggiornamento, in base alla durata dell"aggiornamento. È inoltre necessario conoscere le operazioni che è possibile eseguire e non è possibile eseguire durante ciascuna fase dell"aggiornamento.' 
---
= Stima del tempo necessario per completare un aggiornamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si pianifica un aggiornamento a StorageGRID 11.6, è necessario prendere in considerazione quando eseguire l'aggiornamento, in base alla durata dell'aggiornamento. È inoltre necessario conoscere le operazioni che è possibile eseguire e non è possibile eseguire durante ciascuna fase dell'aggiornamento.

.A proposito di questa attività
Il tempo necessario per completare un aggiornamento di StorageGRID dipende da una varietà di fattori, come il carico del client e le performance dell'hardware.

La tabella riassume le principali attività di aggiornamento ed elenca il tempo approssimativo necessario per ciascuna attività. I passaggi successivi alla tabella forniscono le istruzioni da utilizzare per stimare il tempo di aggiornamento del sistema.

[cols="1a,1a,1a,a"]
|===
| Attività di upgrade | Descrizione | Tempo approssimativo richiesto | Durante questa attività 


 a| 
Avviare il servizio di aggiornamento
 a| 
Vengono eseguiti i controlli preliminari per l'aggiornamento, il file software viene distribuito e viene avviato il servizio di aggiornamento.
 a| 
3 minuti per nodo griglia, a meno che non vengano segnalati errori di convalida
 a| 
Se necessario, è possibile eseguire manualmente i controlli preliminari per l'aggiornamento prima della finestra di manutenzione pianificata per l'aggiornamento.



 a| 
Nodi upgrade Grid (nodo amministratore primario)
 a| 
Il nodo di amministrazione primario viene arrestato, aggiornato e riavviato.
 a| 
Da 30 minuti a 1 ora, con nodi appliance SG100 e SG1000 che richiedono il maggior numero di tempi.
 a| 
Non è possibile accedere al nodo di amministrazione primario. Vengono segnalati errori di connessione che è possibile ignorare.



 a| 
Upgrade Grid Node (tutti gli altri nodi)
 a| 
Il software su tutti gli altri nodi griglia viene aggiornato nell'ordine in cui vengono approvati i nodi. Ogni nodo del sistema verrà spento uno alla volta per diversi minuti ciascuno.
 a| 
da 15 minuti a 1 ora per nodo, con nodi appliance che richiedono il maggior numero di tempo

*Nota:* per i nodi appliance, il programma di installazione dell'appliance StorageGRID viene aggiornato automaticamente alla versione più recente.
 a| 
* Non modificare la configurazione della griglia.
* Non modificare la configurazione del livello di audit.
* Non aggiornare la configurazione ILM.
* Non è possibile eseguire altre procedure di manutenzione, ad esempio hotfix, decommissionare o espandere.
+
*Nota:* se è necessario eseguire un ripristino, contattare il supporto tecnico.





 a| 
Abilitare le funzioni
 a| 
Le nuove funzioni della nuova versione sono attivate.
 a| 
Meno di 5 minuti
 a| 
* Non modificare la configurazione della griglia.
* Non modificare la configurazione del livello di audit.
* Non aggiornare la configurazione ILM.
* Non è possibile eseguire un'altra procedura di manutenzione.




 a| 
Aggiornare il database
 a| 
Il processo di aggiornamento controlla ciascun nodo per verificare che il database Cassandra non debba essere aggiornato.
 a| 
10 secondi per nodo o pochi minuti per l'intera griglia
 a| 
L'aggiornamento da StorageGRID 11.5 a 11.6 non richiede un aggiornamento del database Cassandra; tuttavia, il servizio Cassandra verrà arrestato e riavviato su ciascun nodo di storage.

Per le future versioni delle funzionalità di StorageGRID, il completamento della fase di aggiornamento del database Cassandra potrebbe richiedere diversi giorni.



 a| 
Fasi finali dell'aggiornamento
 a| 
I file temporanei vengono rimossi e l'aggiornamento alla nuova release viene completato.
 a| 
5 minuti
 a| 
Una volta completata l'attività *fasi finali dell'aggiornamento*, è possibile eseguire tutte le procedure di manutenzione.

|===
.Fasi
. Stima del tempo necessario per l'aggiornamento di tutti i nodi della griglia.
+
.. Moltiplicare il numero di nodi nel sistema StorageGRID per 1 ora/nodo.
+
Come regola generale, l'aggiornamento dei nodi appliance richiede più tempo rispetto ai nodi basati su software.

.. Aggiungere 1 ora a questo intervallo di tempo per tenere conto del tempo necessario per scaricare `.upgrade` archiviare, eseguire le validazioni di pre-controllo e completare le fasi finali dell'aggiornamento.


. Se si dispone di nodi Linux, aggiungere 15 minuti per ciascun nodo per tenere conto del tempo necessario per scaricare e installare il pacchetto RPM o DEB.
. Calcola il tempo totale stimato per l'aggiornamento aggiungendo i risultati dei passaggi 1 e 2.




== Esempio: Tempo stimato per l'aggiornamento a StorageGRID 11.6

Si supponga che il sistema disponga di 14 nodi grid, di cui 8 nodi Linux.

. Moltiplicare 14 per 1 ora/nodo.
. Aggiungere 1 ora per tenere conto del download, del controllo preliminare e dei passaggi finali.
+
Il tempo stimato per l'aggiornamento di tutti i nodi è di 15 ore.

. Moltiplicare 8 per 15 minuti/nodo per il tempo di installazione del pacchetto RPM o DEB sui nodi Linux.
+
Il tempo stimato per questa fase è di 2 ore.

. Sommare i valori.
+
L'aggiornamento del sistema a StorageGRID 11.6 deve durare fino a 17 ore.


