---
permalink: sg100-1000/reviewing-appliance-network-connections-sg100-and-sg1000.html 
sidebar: sidebar 
keywords: storagegrid, sg100, sg1000, service appliance, services appliance, gateway Node, admin node, network connections, network connection, network, connection, grid, admin, client, bmc, management 
summary: 'Prima di installare l"appliance StorageGRID, è necessario conoscere le reti che è possibile collegare all"appliance.' 
---
= Verifica delle connessioni di rete dell'appliance (SG100 e SG1000)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di installare l'appliance StorageGRID, è necessario conoscere le reti che è possibile collegare all'appliance.

Quando si implementa un'appliance StorageGRID come nodo in un sistema StorageGRID, è possibile collegarla alle seguenti reti:

* *Grid Network per StorageGRID*: La Grid Network viene utilizzata per tutto il traffico StorageGRID interno. Fornisce connettività tra tutti i nodi della rete, in tutti i siti e le subnet. La rete grid è obbligatoria.
* *Rete amministrativa per StorageGRID*: La rete amministrativa è una rete chiusa utilizzata per l'amministrazione e la manutenzione del sistema. La rete di amministrazione è in genere una rete privata e non deve essere instradabile tra i siti. La rete di amministrazione è opzionale.
* *Rete client per StorageGRID:* la rete client è una rete aperta utilizzata per fornire l'accesso alle applicazioni client, tra cui S3 e Swift. La rete client fornisce l'accesso del protocollo client alla griglia, in modo che la rete griglia possa essere isolata e protetta. È possibile configurare la rete client in modo che sia possibile accedere all'appliance tramite questa rete utilizzando solo le porte che si sceglie di aprire. La rete client è opzionale.
* *BMC management network for the Services appliance* (opzionale): Questa rete fornisce l'accesso al controller di gestione della baseboard in SG100 e SG1000, appliance che consentono di monitorare e gestire i componenti hardware dell'appliance. Questa rete di gestione può essere la stessa della rete di amministrazione per StorageGRID o può essere una rete di gestione indipendente.
+
Se la rete di gestione BMC opzionale non è connessa, alcune procedure di supporto e manutenzione saranno più difficili da eseguire. È possibile lasciare la rete di gestione BMC non connessa, tranne quando necessario per scopi di supporto.



.Informazioni correlate
xref:gathering-installation-information-sg100-and-sg1000.adoc[Raccogliere informazioni sull'installazione (SG100 e SG1000)]

xref:cabling-appliance-sg100-and-sg1000.adoc[Apparecchi via cavo SG100 e SG1000]

xref:../network/index.adoc[Linee guida per il networking]

xref:../primer/index.adoc[Primer griglia]
