---
permalink: sg100-1000/shut-down-sg100-and-sg1000.html 
sidebar: sidebar 
keywords: storagegrid, sg1000, SG100, power off, turn off, shut off, shutdown, shut down, 
summary: 'Spegnere l"appliance di servizi per eseguire la manutenzione dell"hardware.' 
---
= Spegnere l'appliance di servizi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Spegnere l'appliance di servizi per eseguire la manutenzione dell'hardware.

.Di cosa hai bisogno
* L'appliance di servizi che richiede manutenzione è stata fisicamente collocata nel data center.
+
xref:locating-controller-in-data-center.adoc[Individuazione del controller in un data center]

* L'apparecchio è stato utilizzato xref:placing-appliance-into-maintenance-mode.adoc[in modalità di manutenzione].


.A proposito di questa attività
Per evitare interruzioni del servizio, spegnere l'appliance di servizi durante una finestra di manutenzione programmata quando sono normalmente previsti periodi di interruzione del servizio.

.Fasi
. Una volta impostato il modo di manutenzione, spegnere l'apparecchio:
+

CAUTION: È necessario eseguire uno spegnimento controllato dell'apparecchio immettendo i comandi specificati di seguito. Spegnendo l'apparecchio utilizzando l'interruttore di alimentazione si verificherà una perdita di dati.

+
.. Accedere al nodo grid utilizzando putty o un altro client ssh:
+
... Immettere il seguente comando: `ssh admin@_grid_node_IP_`
... Immettere la password elencata in `Passwords.txt` file.
... Immettere il seguente comando per passare a root: `su -`
... Immettere la password elencata in `Passwords.txt` file.
+
Una volta effettuato l'accesso come root, il prompt cambia da `$` a. `#`.



.. Spegnere l'appliance di servizi: +
`*shutdown -h now*`
+
Il completamento di questo comando potrebbe richiedere fino a 10 minuti.



. Utilizzare uno dei seguenti metodi per verificare che l'apparecchio sia spento:
+
** Controllare il LED di alimentazione sulla parte anteriore dell'apparecchio e verificare che sia spento.
** Controllare la pagina Power Control dell'interfaccia BMC per verificare che l'apparecchio sia spento.



