---
permalink: harden/hardening-guidelines-for-software-upgrades.html 
sidebar: sidebar 
keywords: Hardening guidelines, upgrades 
summary: Per difenderti dagli attacchi, devi tenere aggiornato il tuo sistema StorageGRID e i servizi correlati. 
---
= Linee guida per la protezione avanzata degli aggiornamenti software
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per difenderti dagli attacchi, devi tenere aggiornato il tuo sistema StorageGRID e i servizi correlati.



== Aggiornamenti al software StorageGRID

Se possibile, è necessario aggiornare il software StorageGRID alla versione principale più recente o alla versione principale precedente. Mantenere aggiornato StorageGRID aiuta a ridurre il tempo di attivazione delle vulnerabilità note e l'area complessiva della superficie di attacco. Inoltre, le versioni più recenti di StorageGRID contengono spesso funzionalità di protezione avanzata che non sono incluse nelle versioni precedenti.

Quando è necessaria una correzione rapida, NetApp assegna la priorità alla creazione di aggiornamenti per le release più recenti. Alcune patch potrebbero non essere compatibili con le release precedenti.

Per scaricare le versioni più recenti di StorageGRID e gli aggiornamenti rapidi, accedere alla pagina di download del software StorageGRID. Per istruzioni dettagliate sull'aggiornamento del software StorageGRID, consultare le istruzioni per l'aggiornamento di StorageGRID. Per istruzioni sull'applicazione di una correzione rapida, consultare le istruzioni di ripristino e manutenzione.



== Aggiornamenti a servizi esterni

I servizi esterni possono presentare vulnerabilità che influiscono indirettamente su StorageGRID. Devi assicurarti che i servizi da cui dipende StorageGRID siano sempre aggiornati. Questi servizi includono LDAP, KMS (o server KMIP), DNS e NTP.

Utilizza NetApp Interoperability Matrix Tool per ottenere un elenco delle versioni supportate.



== Aggiornamenti agli hypervisor

Se i nodi StorageGRID sono in esecuzione su VMware o su un altro hypervisor, è necessario assicurarsi che il software e il firmware dell'hypervisor siano aggiornati.

Utilizza NetApp Interoperability Matrix Tool per ottenere un elenco delle versioni supportate.



== *Upgrade a nodi Linux*

Se i nodi StorageGRID utilizzano piattaforme host Linux, è necessario assicurarsi che gli aggiornamenti di sicurezza e del kernel siano applicati al sistema operativo host. Inoltre, è necessario applicare gli aggiornamenti del firmware all'hardware vulnerabile quando questi aggiornamenti diventano disponibili.

Utilizza NetApp Interoperability Matrix Tool per ottenere un elenco delle versioni supportate.

.Informazioni correlate
https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["Download NetApp: StorageGRID"^]

xref:../upgrade/index.adoc[Aggiornare il software]

xref:../maintain/index.adoc[Ripristino e manutenzione]

https://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità NetApp"^]
