---
permalink: network/internal-grid-node-communications.html 
sidebar: sidebar 
keywords: storagegrid, network port, internal communications, ports, TCP, UDP, grid communications 
summary: 'Il firewall interno di StorageGRID consente solo connessioni in entrata a porte specifiche della rete di rete, ad eccezione delle porte 22, 80, 123 e 443 (vedere le informazioni relative alle comunicazioni esterne). Le connessioni sono accettate anche sulle porte definite dagli endpoint del bilanciamento del carico.' 
---
= Comunicazioni interne al nodo di rete
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il firewall interno di StorageGRID consente solo connessioni in entrata a porte specifiche della rete di rete, ad eccezione delle porte 22, 80, 123 e 443 (vedere le informazioni sulle comunicazioni esterne). Le connessioni sono accettate anche sulle porte definite dagli endpoint del bilanciamento del carico.


NOTE: NetApp consiglia di attivare il traffico ICMP (Internet Control message Protocol) tra i nodi di rete. Consentire il traffico ICMP può migliorare le prestazioni di failover quando non è possibile raggiungere un nodo di rete.

Oltre a ICMP e alle porte elencate nella tabella, StorageGRID utilizza il protocollo di ridondanza del router virtuale (VRRP). VRRP è un protocollo Internet che utilizza il protocollo IP numero 112. StorageGRID utilizza VRRP solo in modalità unicast. VRRP è richiesto solo se xref:../admin/managing-high-availability-groups.adoc[gruppi ad alta disponibilità] sono configurati.



== Linee guida per i nodi basati su Linux

Se i criteri di rete aziendali limitano l'accesso a una di queste porte, è possibile rimappare le porte in fase di implementazione utilizzando un parametro di configurazione dell'implementazione. Per ulteriori informazioni sul remapping delle porte e sui parametri di configurazione della distribuzione, vedere:

* xref:../rhel/index.adoc[Installare Red Hat Enterprise Linux o CentOS]
* xref:../ubuntu/index.adoc[Installare Ubuntu o Debian]




== Linee guida per i nodi basati su VMware

Configurare le seguenti porte solo se è necessario definire restrizioni firewall esterne alla rete VMware.

Se i criteri di rete aziendali limitano l'accesso a una qualsiasi di queste porte, è possibile rimappare le porte quando si implementano nodi utilizzando VMware vSphere Web Client o utilizzando un'impostazione del file di configurazione quando si automatizza l'implementazione del nodo grid. Per ulteriori informazioni sul remapping delle porte e sui parametri di configurazione della distribuzione, vederexref:../vmware/index.adoc[Installare VMware].



== Linee guida per i nodi appliance

Se i criteri di rete aziendali limitano l'accesso a una di queste porte, è possibile rimappare le porte utilizzando il programma di installazione dell'appliance StorageGRID. Per ulteriori informazioni sul rimapping delle porte per le appliance, consulta:

* xref:../sg100-1000/index.adoc[Appliance di servizi SG100 e SG1000]
* xref:../sg6000/index.adoc[Appliance di storage SG6000]
* xref:../sg5700/index.adoc[Appliance di storage SG5700]
* xref:../sg5600/index.adoc[Appliance di storage SG5600]




== Porte interne StorageGRID

|===


| Porta | TCP o UDP | Da | A. | Dettagli 


 a| 
22
 a| 
TCP
 a| 
Nodo amministratore primario
 a| 
Tutti i nodi
 a| 
Per le procedure di manutenzione, il nodo di amministrazione primario deve essere in grado di comunicare con tutti gli altri nodi utilizzando SSH sulla porta 22. Consentire il traffico SSH da altri nodi è facoltativo.



 a| 
80
 a| 
TCP
 a| 
Appliance
 a| 
Nodo amministratore primario
 a| 
Utilizzato dalle appliance StorageGRID per comunicare con il nodo di amministrazione principale per avviare l'installazione.



 a| 
123
 a| 
UDP
 a| 
Tutti i nodi
 a| 
Tutti i nodi
 a| 
Servizio Network Time Protocol. Ogni nodo sincronizza il proprio tempo con ogni altro nodo utilizzando NTP.



 a| 
443
 a| 
TCP
 a| 
Tutti i nodi
 a| 
Nodo amministratore primario
 a| 
Utilizzato per comunicare lo stato al nodo di amministrazione primario durante l'installazione e altre procedure di manutenzione.



 a| 
1139
 a| 
TCP
 a| 
Nodi di storage
 a| 
Nodi di storage
 a| 
Traffico interno tra nodi di storage.



 a| 
1501
 a| 
TCP
 a| 
Tutti i nodi
 a| 
Nodi di storage con ADC
 a| 
Traffico interno di reporting, controllo e configurazione.



 a| 
1502
 a| 
TCP
 a| 
Tutti i nodi
 a| 
Nodi di storage
 a| 
Traffico interno correlato a S3 e Swift.



 a| 
1504
 a| 
TCP
 a| 
Tutti i nodi
 a| 
Nodi di amministrazione
 a| 
Traffico interno di configurazione e reporting del servizio NMS.



 a| 
1505
 a| 
TCP
 a| 
Tutti i nodi
 a| 
Nodi di amministrazione
 a| 
Traffico interno del servizio AMS.



 a| 
1506
 a| 
TCP
 a| 
Tutti i nodi
 a| 
Tutti i nodi
 a| 
Traffico interno dello stato del server.



 a| 
1507
 a| 
TCP
 a| 
Tutti i nodi
 a| 
Nodi gateway
 a| 
Traffico interno del bilanciamento del carico.



 a| 
1508
 a| 
TCP
 a| 
Tutti i nodi
 a| 
Nodo amministratore primario
 a| 
Traffico interno della gestione della configurazione.



 a| 
1509
 a| 
TCP
 a| 
Tutti i nodi
 a| 
Nodi di archiviazione
 a| 
Traffico interno del nodo di archiviazione.



 a| 
1511
 a| 
TCP
 a| 
Tutti i nodi
 a| 
Nodi di storage
 a| 
Traffico interno dei metadati.



 a| 
5353
 a| 
UDP
 a| 
Tutti i nodi
 a| 
Tutti i nodi
 a| 
Utilizzato come opzione per le modifiche dell'IP full-grid e per il rilevamento del nodo di amministrazione primario durante l'installazione, l'espansione e il ripristino.



 a| 
7001
 a| 
TCP
 a| 
Nodi di storage
 a| 
Nodi di storage
 a| 
Comunicazione cluster tra nodi Cassandra TLS.



 a| 
7443
 a| 
TCP
 a| 
Tutti i nodi
 a| 
Nodi di amministrazione
 a| 
Traffico interno per le procedure di manutenzione e la segnalazione degli errori.



| 8443 | TCP | Nodo amministratore primario | Nodi appliance | Traffico interno relativo alla procedura della modalità di manutenzione. 


 a| 
9042
 a| 
TCP
 a| 
Nodi di storage
 a| 
Nodi di storage
 a| 
Porta client Cassandra.



 a| 
9999
 a| 
TCP
 a| 
Tutti i nodi
 a| 
Tutti i nodi
 a| 
Traffico interno per più servizi. Include procedure di manutenzione, metriche e aggiornamenti di rete.



 a| 
10226
 a| 
TCP
 a| 
Nodi di storage
 a| 
Nodo amministratore primario
 a| 
Utilizzato dalle appliance StorageGRID per l'inoltro dei messaggi AutoSupport da Gestione di sistema di e-Series SANtricity al nodo di amministrazione primario.



 a| 
11139
 a| 
TCP
 a| 
Nodi di archiviazione/storage
 a| 
Nodi di archiviazione/storage
 a| 
Traffico interno tra nodi di storage e nodi di archiviazione.



 a| 
18000
 a| 
TCP
 a| 
Nodi Admin/Storage
 a| 
Nodi di storage con ADC
 a| 
Traffico interno del servizio account.



 a| 
18001
 a| 
TCP
 a| 
Nodi Admin/Storage
 a| 
Nodi di storage con ADC
 a| 
Traffico interno di Identity Federation.



 a| 
18002
 a| 
TCP
 a| 
Nodi Admin/Storage
 a| 
Nodi di storage
 a| 
Traffico API interno correlato ai protocolli a oggetti.



 a| 
18003
 a| 
TCP
 a| 
Nodi Admin/Storage
 a| 
Nodi di storage con ADC
 a| 
Traffico interno dei servizi della piattaforma.



 a| 
18017
 a| 
TCP
 a| 
Nodi Admin/Storage
 a| 
Nodi di storage
 a| 
Traffico interno del servizio Data Mover per i pool di storage cloud.



 a| 
18019
 a| 
TCP
 a| 
Nodi di storage
 a| 
Nodi di storage
 a| 
Traffico interno del servizio di chunk per la cancellazione del codice.



 a| 
18082
 a| 
TCP
 a| 
Nodi Admin/Storage
 a| 
Nodi di storage
 a| 
Traffico interno correlato a S3.



 a| 
18083
 a| 
TCP
 a| 
Tutti i nodi
 a| 
Nodi di storage
 a| 
Traffico interno correlato a Swift.



 a| 
18200
 a| 
TCP
 a| 
Nodi Admin/Storage
 a| 
Nodi di storage
 a| 
Statistiche aggiuntive sulle richieste dei client.



 a| 
19000
 a| 
TCP
 a| 
Nodi Admin/Storage
 a| 
Nodi di storage con ADC
 a| 
Traffico interno del servizio Keystone.

|===
*Informazioni correlate*

xref:external-communications.adoc[Comunicazioni esterne]
