---
permalink: sg5600/verifying-receipt-of-autosupport.html 
sidebar: sidebar 
keywords: storagegrid, sg5600, storage node, storage appliance, verify, verification, verifying, confirm, confirmation, confirming, autosupport, auto-support, status 
summary: Verificare che il supporto tecnico stia ricevendo i messaggi AutoSupport. Puoi trovare lo stato di AutoSupport per i tuoi sistemi sul portale Active IQ. La verifica della ricezione di questi messaggi garantisce che il supporto tecnico disponga delle informazioni necessarie in caso di necessità. 
---
= Verificare la ricezione di AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Verificare che il supporto tecnico stia ricevendo i messaggi AutoSupport. Puoi trovare lo stato di AutoSupport per i tuoi sistemi sul portale Active IQ. La verifica della ricezione di questi messaggi garantisce che il supporto tecnico disponga delle informazioni necessarie in caso di necessità.

.A proposito di questa attività
AutoSupport può mostrare uno dei seguenti stati:

* *ACCESO*
+
Lo stato ON indica che il supporto tecnico sta attualmente ricevendo messaggi AutoSupport dal sistema.

* *OFF*
+
Uno stato di disattivazione suggerisce di aver disattivato AutoSupport perché il supporto tecnico non ha ricevuto un registro settimanale dal sistema negli ultimi 15 giorni di calendario o potrebbe essere stata apportata una modifica all'ambiente o alla configurazione (ad esempio).

* *RIFIUTARE*
+
Uno stato DI RIFIUTO indica che hai notificato al supporto tecnico che non abiliterai AutoSupport.



Dopo che il supporto tecnico riceve un registro settimanale dal sistema, lo stato AutoSupport diventa ON.

.Fasi
. Visitare il sito del supporto NetApp all'indirizzo http://mysupport.netapp.com/["mysupport.netapp.com"^]E accedere al portale Active IQ.
. Se lo stato AutoSupport è OFF e si ritiene che non sia corretto, completare le seguenti operazioni:
+
.. Verificare la configurazione del sistema per assicurarsi di aver attivato AutoSupport.
.. Controllare l'ambiente di rete e la configurazione per assicurarsi che il sistema possa inviare messaggi al supporto tecnico.



