---
permalink: admin/archiving-to-cloud-through-s3-api.html 
sidebar: sidebar 
keywords: archive node to aws, amazon web services 
summary: 'È possibile configurare un nodo di archiviazione per la connessione diretta ai servizi Web Amazon o a qualsiasi altro sistema in grado di interfacciarsi con il sistema StorageGRID tramite l"API S3.' 
---
= Archiviazione nel cloud tramite l'API S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile configurare un nodo di archiviazione per la connessione diretta ai servizi Web Amazon o a qualsiasi altro sistema in grado di interfacciarsi con il sistema StorageGRID tramite l'API S3.


IMPORTANT: Lo spostamento di oggetti da un nodo di archiviazione a un sistema storage di archiviazione esterno tramite l'API S3 è stato sostituito da pool di storage cloud ILM, che offrono maggiori funzionalità. L'opzione *Cloud Tiering - Simple Storage Service (S3)* è ancora supportata, ma potresti preferire implementare i Cloud Storage Pool.

Se stai utilizzando un nodo di archiviazione con l'opzione *Cloud Tiering - Simple Storage Service (S3)*, prendi in considerazione la migrazione degli oggetti a un pool di storage cloud. Consultare le istruzioni per xref:../ilm/index.adoc[Gestione degli oggetti con ILM].
