---
permalink: admin/manage-s3-select-for-tenant-accounts.html 
sidebar: sidebar 
keywords: s3 select, selectobjectcontent, best practices 
summary: È possibile consentire a determinati tenant S3 di utilizzare S3 Select per emettere richieste SelectObjectContent su singoli oggetti. 
---
= Manage S3 (Gestisci S3): Selezionare per gli account tenant
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile consentire a determinati tenant S3 di utilizzare S3 Select per emettere richieste SelectObjectContent su singoli oggetti.

S3 Select offre un modo efficiente per cercare grandi quantità di dati senza dover implementare un database e le risorse associate per abilitare le ricerche. Inoltre, riduce i costi e la latenza del recupero dei dati.



== Che cos'è S3 Select?

S3 Select consente ai client S3 di utilizzare le richieste SelectObjectContent per filtrare e recuperare solo i dati necessari da un oggetto. L'implementazione StorageGRID di S3 Select include un sottoinsieme di comandi e funzionalità S3 Select.



== Considerazioni e requisiti per l'utilizzo di S3 Select

StorageGRID richiede quanto segue per le query S3 Select:

* L'oggetto che si desidera sottoporre a query è in formato CSV oppure è un file compresso GZIP o BZIP2 contenente un file in formato CSV.
* Ai tenant deve essere concessa l'abilità S3 Select dall'amministratore della griglia. Selezionare *Allow S3 Select* when (Consenti selezione S3) xref:creating-tenant-account.adoc[creazione di un tenant] oppure xref:editing-tenant-account.adoc[modifica di un tenant].
* La richiesta SelectObjectContent deve essere inviata a xref:configuring-load-balancer-endpoints.adoc[Endpoint del bilanciamento del carico di StorageGRID]. I nodi Admin e Gateway utilizzati dall'endpoint devono essere nodi appliance SG100 o SG1000 o nodi software basati su VMware.


Tenere presente le seguenti limitazioni:

* I nodi bare-metal di bilanciamento del carico non sono supportati.
* Le query non possono essere inviate direttamente ai nodi di storage.
* Le query inviate tramite il servizio CLB obsoleto non sono supportate.



IMPORTANT: Le richieste SelectObjectContent possono ridurre le performance di bilanciamento del carico per tutti i client S3 e per tutti i tenant. Attivare questa funzione solo quando richiesto e solo per tenant attendibili.

Vedere xref:../s3/use-s3-select.adoc[Istruzioni per l'utilizzo di S3 Select].

Per visualizzare xref:../monitor/reviewing-support-metrics.adoc[Grafici Grafana] Per le operazioni S3 Select nel tempo, selezionare *SUPPORT* *Tools* *Metrics* in Grid Manager.
