---
permalink: s3/head-object.html 
sidebar: sidebar 
keywords: head object 
summary: 'È possibile utilizzare la richiesta di oggetti TESTA S3 per recuperare i metadati da un oggetto senza restituire l"oggetto stesso.' 
---
= Oggetto TESTA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare la richiesta di oggetti TESTA S3 per recuperare i metadati da un oggetto senza restituire l'oggetto stesso. Se l'oggetto è memorizzato in un Cloud Storage Pool, è possibile utilizzare l'oggetto HEAD per determinare lo stato di transizione dell'oggetto.



== OGGETTI TESTA e multiparte

È possibile utilizzare `partNumber` richiedi il parametro per recuperare i metadati per una parte specifica di un oggetto multiparte o segmentato. Il `x-amz-mp-parts-count` l'elemento response indica il numero di parti dell'oggetto.

È possibile impostare `partNumber` a 1 per oggetti segmentati/multiparte e non segmentati/non multiparte; tuttavia, il `x-amz-mp-parts-count` l'elemento di risposta viene restituito solo per gli oggetti segmentati o multiparte.



== Intestazioni delle richieste per la crittografia lato server con chiavi di crittografia fornite dal cliente (SSE-C)

Utilizzare tutte e tre queste intestazioni se l'oggetto è crittografato con una chiave univoca fornita dall'utente.

* `x-amz-server-side-encryption-customer-algorithm`: Specificare `AES256`.
* `x-amz-server-side-encryption-customer-key`: Specificare la chiave di crittografia per l'oggetto.
* `x-amz-server-side-encryption-customer-key-MD5`: Specificare il digest MD5 della chiave di crittografia dell'oggetto.



IMPORTANT: Le chiavi di crittografia fornite non vengono mai memorizzate. Se si perde una chiave di crittografia, si perde l'oggetto corrispondente. Prima di utilizzare le chiavi fornite dal cliente per proteggere i dati degli oggetti, consultare le considerazioni in "`Usa crittografia lato server`".



== UTF-8 caratteri nei metadati dell'utente

StorageGRID non analizza o interpreta i caratteri UTF-8 escapati nei metadati definiti dall'utente. Le richieste HEAD per un oggetto con caratteri UTF-8 escapati nei metadati definiti dall'utente non restituiscono `x-amz-missing-meta` intestazione se il nome o il valore della chiave include caratteri non stampabili.



== Intestazione della richiesta non supportata

La seguente intestazione di richiesta non è supportata e restituisce `XNotImplemented`:

* `x-amz-website-redirect-location`




== Intestazioni di risposta per gli oggetti del Cloud Storage Pool

Se l'oggetto viene memorizzato in un Cloud Storage Pool (vedere le istruzioni per la gestione degli oggetti con gestione del ciclo di vita delle informazioni), vengono restituite le seguenti intestazioni di risposta:

* `x-amz-storage-class: GLACIER`
* `x-amz-restore`


Le intestazioni delle risposte forniscono informazioni sullo stato di un oggetto quando viene spostato in un Cloud Storage Pool, facoltativamente trasferito in uno stato non recuperabile e ripristinato.

|===
| Stato dell'oggetto | Risposta all'oggetto HEAD 


 a| 
Oggetto acquisito in StorageGRID ma non ancora valutato da ILM, o oggetto memorizzato in un pool di storage tradizionale o mediante erasure coding
 a| 
`200 OK` (Non viene restituita alcuna intestazione di risposta speciale).



 a| 
Oggetto nel Cloud Storage Pool ma non ancora passato a uno stato non recuperabile
 a| 
`200 OK`

`x-amz-storage-class: GLACIER`

`x-amz-restore: ongoing-request="false", expiry-date="Sat, 23 July 20 2030 00:00:00 GMT"`

Fino a quando l'oggetto non passa a uno stato non recuperabile, il valore per `expiry-date` è impostato su un periodo di tempo lontano in futuro. L'ora esatta della transizione non è controllata dal sistema StorageGRID.



 a| 
L'oggetto è passato allo stato non recuperabile, ma almeno una copia esiste anche nella griglia
 a| 
`200 OK`

`x-amz-storage-class: GLACIER`

`x-amz-restore: ongoing-request="false", expiry-date="Sat, 23 July 20 2030 00:00:00 GMT"`

Il valore per `expiry-date` è impostato su un periodo di tempo lontano in futuro.

*Nota*: Se la copia sulla griglia non è disponibile (ad esempio, un nodo di storage è inattivo), è necessario eseguire una richiesta DI ripristino DELL'oggetto POST per ripristinare la copia dal pool di storage cloud prima di poter recuperare l'oggetto.



 a| 
L'oggetto è passato a uno stato non recuperabile e non esiste alcuna copia nella griglia
 a| 
`200 OK`

`x-amz-storage-class: GLACIER`



 a| 
Oggetto in fase di ripristino da uno stato non recuperabile
 a| 
`200 OK`

`x-amz-storage-class: GLACIER`

`x-amz-restore: ongoing-request="true"`



 a| 
Oggetto completamente ripristinato nel Cloud Storage Pool
 a| 
`200 OK`

`x-amz-storage-class: GLACIER`

`x-amz-restore: ongoing-request="false", expiry-date="Sat, 23 July 20 2018 00:00:00 GMT"`

Il `expiry-date` Indica quando l'oggetto nel Cloud Storage Pool verrà riportato in uno stato non recuperabile.

|===


== Oggetti multiparte o segmentati nel Cloud Storage Pool

Se hai caricato un oggetto multiparte o se StorageGRID divide un oggetto di grandi dimensioni in segmenti, StorageGRID determina se l'oggetto è disponibile nel pool di storage cloud campionando un sottoinsieme delle parti o dei segmenti dell'oggetto. In alcuni casi, la richiesta di un oggetto HEAD potrebbe non essere corretta `x-amz-restore: ongoing-request="false"` quando alcune parti dell'oggetto sono già state trasferite in uno stato non recuperabile o quando alcune parti dell'oggetto non sono ancora state ripristinate.



== Versione

Se si seleziona `versionId` la sottorisorsa non viene specificata, l'operazione recupera la versione più recente dell'oggetto in un bucket con versione. Se la versione corrente dell'oggetto è un indicatore di eliminazione, viene restituito lo stato "`Not Found`" (non trovato) con `x-amz-delete-marker` intestazione risposta impostata su `true`.

.Informazioni correlate
xref:using-server-side-encryption.adoc[Utilizzare la crittografia lato server]

xref:../ilm/index.adoc[Gestire gli oggetti con ILM]

xref:post-object-restore.adoc[RIPRISTINO POST-oggetto]

xref:s3-operations-tracked-in-audit-logs.adoc[Operazioni S3 monitorate nei registri di audit]
