---
permalink: s3/operations-on-the-service.html 
sidebar: sidebar 
keywords: operations, service, operations on the service 
summary: Il sistema StorageGRID supporta le operazioni sul servizio. 
---
= Operazioni sul servizio
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il sistema StorageGRID supporta le seguenti operazioni sul servizio.

|===
| Operazione | Implementazione 


 a| 
OTTIENI assistenza
 a| 
Implementato con tutti i comportamenti REST API di Amazon S3.



 a| 
OTTIENI l'utilizzo dello storage
 a| 
La richiesta GET Storage Usage indica la quantità totale di storage in uso da un account e per ciascun bucket associato all'account. Si tratta di un'operazione sul servizio con un percorso di / e un parametro di query personalizzato (`?x-ntap-sg-usage`) aggiunto.



 a| 
OPZIONI /
 a| 
Le applicazioni client possono avere problemi `OPTIONS /` Richiede alla porta S3 su un nodo di storage, senza fornire credenziali di autenticazione S3, di determinare se il nodo di storage è disponibile. È possibile utilizzare questa richiesta per il monitoraggio o per consentire ai bilanciatori di carico esterni di identificare quando un nodo di storage è inattivo.

|===
.Informazioni correlate
xref:get-storage-usage-request.adoc[OTTIENI la richiesta di utilizzo dello storage]
