---
permalink: s3/using-s3-object-lock.html 
sidebar: sidebar 
keywords: using S3 object lock, object lock, S3 object 
summary: 'Se l"impostazione blocco oggetti S3 globale è attivata per il sistema StorageGRID, è possibile creare bucket con blocco oggetti S3 attivato e specificare le impostazioni di conservazione fino alla data e conservazione legale per ogni versione dell"oggetto aggiunta a tale bucket.' 
---
= USA blocco oggetti S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se l'impostazione blocco oggetti S3 globale è attivata per il sistema StorageGRID, è possibile creare bucket con blocco oggetti S3 attivato e specificare i periodi di conservazione predefiniti per ciascun bucket o le impostazioni di conservazione fino alla data e alle condizioni legali specifiche per ciascuna versione di oggetto aggiunta a tale bucket.

S3 Object Lock consente di specificare le impostazioni a livello di oggetto per impedire che gli oggetti vengano cancellati o sovrascritti per un periodo di tempo fisso o indefinito.

La funzione blocco oggetto StorageGRID S3 offre una singola modalità di conservazione equivalente alla modalità di conformità Amazon S3. Per impostazione predefinita, una versione dell'oggetto protetto non può essere sovrascritta o eliminata da alcun utente. La funzione blocco oggetti di StorageGRID S3 non supporta una modalità di governance e non consente agli utenti con autorizzazioni speciali di ignorare le impostazioni di conservazione o di eliminare gli oggetti protetti.



== Attiva il blocco oggetti S3 per il bucket

Se l'impostazione globale di blocco oggetti S3 è attivata per il sistema StorageGRID, è possibile attivare il blocco oggetti S3 quando si crea ciascun bucket. È possibile utilizzare uno dei seguenti metodi:

* Creare il bucket utilizzando il tenant Manager.
+
xref:../tenant/index.adoc[USA account tenant]

* Creare il bucket utilizzando una richiesta PUT bucket con `x-amz-bucket-object-lock-enabled` intestazione della richiesta.
+
xref:operations-on-buckets.adoc[Operazioni sui bucket]



Non è possibile aggiungere o disattivare il blocco oggetti S3 dopo la creazione del bucket. S3 Object Lock richiede il controllo della versione del bucket, che viene attivato automaticamente quando si crea il bucket.

Un bucket con S3 Object Lock abilitato può contenere una combinazione di oggetti con e senza le impostazioni S3 Object Lock. StorageGRID supporta i periodi di conservazione predefiniti per gli oggetti nei bucket blocco oggetti S3 e supporta l'operazione DEL bucket DI configurazione BLOCCO oggetti PUT. Il `s3:object-lock-remaining-retention-days` policy condition key imposta i periodi di conservazione minimi e massimi consentiti per gli oggetti.



== Determinare se il blocco oggetti S3 è attivato per il bucket

Per determinare se il blocco oggetti S3 è attivato, utilizzare xref:../s3/use-s3-object-lock-default-bucket-retention.adoc#get-object-lock-configuration[OTTIENI configurazione blocco oggetto] richiesta.



== Creare un oggetto con le impostazioni di blocco oggetti S3

Per specificare le impostazioni di blocco oggetti S3 quando si aggiunge una versione di oggetto a un bucket con blocco oggetti S3 attivato, eseguire una richiesta PUT object, PUT object - Copy o avviare la richiesta di caricamento multiparte. Utilizzare le seguenti intestazioni di richiesta.


NOTE: È necessario attivare il blocco oggetti S3 quando si crea un bucket. Non è possibile aggiungere o disattivare il blocco oggetti S3 dopo la creazione di un bucket.

* `x-amz-object-lock-mode`, Che deve essere CONFORME (distinzione tra maiuscole e minuscole).
+

NOTE: Se si specifica `x-amz-object-lock-mode`, è inoltre necessario specificare `x-amz-object-lock-retain-until-date`.

* `x-amz-object-lock-retain-until-date`
+
** Il valore di conservazione fino alla data deve essere nel formato `2020-08-10T21:46:00Z`. Sono consentiti i secondi frazionari, ma vengono conservate solo 3 cifre decimali (precisione in millisecondi). Non sono consentiti altri formati ISO 8601.
** La data di conservazione deve essere in futuro.


* `x-amz-object-lock-legal-hold`
+
Se la conservazione legale È ATTIVA (sensibile al maiuscolo/minuscolo), l'oggetto viene collocato sotto una conservazione legale. Se l'opzione Legal Hold è disattivata, non viene effettuata alcuna conservazione a fini giudiziari. Qualsiasi altro valore genera un errore 400 Bad Request (InvalidArgument).



Se si utilizza una di queste intestazioni di richiesta, tenere presente le seguenti restrizioni:

* Il `Content-MD5` l'intestazione della richiesta è obbligatoria, se presente `x-amz-object-lock-*` L'intestazione della richiesta è presente nella richiesta DELL'oggetto PUT. `Content-MD5` Non è richiesto per METTERE oggetto - copiare o avviare caricamento multiparte.
* Se il bucket non ha S3 Object Lock abilitato e un `x-amz-object-lock-*` L'intestazione della richiesta è presente, viene restituito un errore 400 Bad Request (InvalidRequest).
* La richiesta DI oggetti PUT supporta l'utilizzo di `x-amz-storage-class: REDUCED_REDUNDANCY` Per far corrispondere il comportamento di AWS. Tuttavia, quando un oggetto viene acquisito in un bucket con il blocco oggetti S3 attivato, StorageGRID eseguirà sempre un ingest a doppio commit.
* Una risposta successiva ALLA versione DELL'oggetto GET o HEAD includerà le intestazioni `x-amz-object-lock-mode`, `x-amz-object-lock-retain-until-date`, e. `x-amz-object-lock-legal-hold`, se configurato e se il mittente della richiesta ha il corretto `s3:Get*` permessi.
* Una successiva richiesta DI versione DELL'oggetto DELETE o di versioni DELL'oggetto DELETE avrà esito negativo se è precedente alla data di conservazione o se è attiva una conservazione a fini giudiziari.




== Aggiornare le impostazioni di blocco oggetti S3

Se è necessario aggiornare le impostazioni di conservazione o conservazione a fini giudiziari per una versione di oggetto esistente, è possibile eseguire le seguenti operazioni di sottorisorsa oggetto:

* `PUT Object legal-hold`
+
Se IL nuovo valore di conservazione a fini giudiziari è ATTIVO, l'oggetto viene collocato sotto una conservazione a fini giudiziari. Se il valore di conservazione a fini giudiziari è OFF, la conservazione a fini giudiziari viene revocata.

* `PUT Object retention`
+
** Il valore della modalità deve essere COMPLIANCE (distinzione tra maiuscole e minuscole).
** Il valore di conservazione fino alla data deve essere nel formato `2020-08-10T21:46:00Z`. Sono consentiti i secondi frazionari, ma vengono conservate solo 3 cifre decimali (precisione in millisecondi). Non sono consentiti altri formati ISO 8601.
** Se una versione a oggetti ha un valore di conservazione esistente fino alla data odierna, è possibile aumentarlo. Il nuovo valore deve essere in futuro.




.Informazioni correlate
xref:../ilm/index.adoc[Gestire gli oggetti con ILM]

xref:../tenant/index.adoc[USA account tenant]

xref:put-object.adoc[METTI oggetto]

xref:put-object-copy.adoc[METTI oggetto - Copia]

xref:initiate-multipart-upload.adoc[Avvia caricamento multiparte]

xref:object-versioning.adoc[Versione degli oggetti]

https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock.html["Amazon Simple Storage Service User Guide (Guida utente di Amazon Simple Storage Service): Utilizzo di S3 Object Lock"^]
