---
permalink: monitor/commonly-used-prometheus-metrics.html 
sidebar: sidebar 
keywords: prometheus, Prometheus metrics, metrics 
summary: Il servizio Prometheus sui nodi di amministrazione raccoglie le metriche delle serie temporali dai servizi su tutti i nodi. Mentre Prometheus raccoglie più di mille metriche, un numero relativamente piccolo è necessario per monitorare le operazioni StorageGRID più critiche. 
---
= Metriche Prometheus comunemente utilizzate
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il servizio Prometheus sui nodi di amministrazione raccoglie le metriche delle serie temporali dai servizi su tutti i nodi. Mentre Prometheus raccoglie più di mille metriche, un numero relativamente piccolo è necessario per monitorare le operazioni StorageGRID più critiche.

Le metriche vengono memorizzate su ciascun nodo di amministrazione fino a quando lo spazio riservato ai dati Prometheus non è pieno. Quando il `/var/local/mysql_ibdata/` il volume raggiunge la capacità, le metriche meno recenti vengono prima eliminate.

Per ottenere l'elenco completo delle metriche, utilizza l'API Grid Management.

. Nella parte superiore di Grid Manager, selezionare l'icona della guida e selezionare *documentazione API*.
. Individuare le operazioni *metriche*.
. Eseguire `GET /grid/metric-names` operazione.
. Scarica i risultati.


La seguente tabella elenca le metriche Prometheus più comunemente utilizzate. È possibile fare riferimento a questo elenco per comprendere meglio le condizioni nelle regole di avviso predefinite o per creare le condizioni per le regole di avviso personalizzate.


NOTE: Le metriche che includono _private_ nei loro nomi sono destinate esclusivamente all'uso interno e sono soggette a modifiche tra le release di StorageGRID senza preavviso.

|===
| Metrica Prometheus | Descrizione 


 a| 
alertmanager_notifications_failed_total
 a| 
Il numero totale di notifiche di avviso non riuscite.



 a| 
node_filesystem_avail_bytes
 a| 
La quantità di spazio del file system disponibile in byte per gli utenti non root.



 a| 
Node_Memory_MemAvailable_Bytes
 a| 
Campo delle informazioni sulla memoria MemAvailable_Bytes.



 a| 
node_network_carrier
 a| 
Valore portante di /sys/class/net/iface.



 a| 
node_network_receive_errs_total
 a| 
Network Device statytics receive_errs.



 a| 
node_network_transmit_errs_total
 a| 
Network Device statytics transmit_errs.



 a| 
storagegrid_administively_down
 a| 
Il nodo non è connesso alla rete per un motivo previsto. Ad esempio, il nodo o i servizi sul nodo sono stati normalmente spenti, il nodo è in fase di riavvio o il software è in fase di aggiornamento.



 a| 
storagegrid_appliance_compute_controller_hardware_status
 a| 
Lo stato dell'hardware del controller di calcolo in un'appliance.



 a| 
storagegrid_appliance_failed_disks
 a| 
Per lo storage controller di un'appliance, il numero di dischi non ottimali.



 a| 
storagegrid_appliance_storage_controller_hardware_status
 a| 
Lo stato generale dell'hardware dello storage controller in un'appliance.



 a| 
storagegrid_content_bucket_and_containers
 a| 
Il numero totale di bucket S3 e container Swift noti da questo nodo di storage.



 a| 
storagegrid_content_objects
 a| 
Il numero totale di oggetti dati S3 e Swift noti da questo nodo di storage. Il conteggio è valido solo per gli oggetti dati creati dalle applicazioni client che si interfacciano con il sistema tramite S3 o Swift.



 a| 
storagegrid_content_objects_lost
 a| 
Il numero totale di oggetti che il servizio rileva come mancanti dal sistema StorageGRID. È necessario intraprendere azioni per determinare la causa della perdita e se è possibile eseguire il ripristino.

xref:troubleshooting-lost-and-missing-object-data.adoc[Risolvere i problemi relativi ai dati degli oggetti persi e mancanti]



 a| 
storagegrid_http_sessions_incoming_tented
 a| 
Il numero totale di sessioni HTTP che sono state tentate per un nodo di storage.



 a| 
storagegrid_http_sessions_incoming_currently_established
 a| 
Il numero di sessioni HTTP attualmente attive (aperte) sul nodo di storage.



 a| 
storagegrid_http_sessions_incoming_failed
 a| 
Il numero totale di sessioni HTTP che non sono riuscite a completare correttamente, a causa di una richiesta HTTP non valida o di un errore durante l'elaborazione di un'operazione.



 a| 
storagegrid_http_sessions_incoming_successful
 a| 
Il numero totale di sessioni HTTP completate correttamente.



 a| 
storagegrid_ilm_waiting_background_objects
 a| 
Il numero totale di oggetti su questo nodo in attesa di valutazione ILM dalla scansione.



 a| 
storagegrid_ilm_waiting_client_evaluation_objects_per_second
 a| 
La velocità corrente alla quale gli oggetti vengono valutati in base al criterio ILM su questo nodo.



 a| 
storagegrid_ilm_waiting_client_objects
 a| 
Il numero totale di oggetti su questo nodo in attesa di valutazione ILM dalle operazioni del client (ad esempio, acquisizione).



 a| 
storagegrid_ilm_waiting_total_objects
 a| 
Il numero totale di oggetti in attesa di valutazione ILM.



 a| 
storagegrid_ilm_scan_objects_per_second
 a| 
La velocità con cui gli oggetti di proprietà di questo nodo vengono sottoposti a scansione e messi in coda per ILM.



 a| 
storagegrid_ilm_scan_period_estimated_minutes
 a| 
Il tempo stimato per completare una scansione ILM completa su questo nodo.

*Nota:* Una scansione completa non garantisce che ILM sia stato applicato a tutti gli oggetti di proprietà di questo nodo.



 a| 
storagegrid_load_balancer_endpoint_cert_expiry_time
 a| 
Il tempo di scadenza del certificato endpoint del bilanciamento del carico in secondi dall'epoca.



 a| 
storagegrid_metadata_queries_average_latency_millisecondi
 a| 
Il tempo medio richiesto per eseguire una query sull'archivio di metadati tramite questo servizio.



 a| 
storagegrid_network_received_bytes
 a| 
La quantità totale di dati ricevuti dall'installazione.



 a| 
storagegrid_network_transmitted_bytes
 a| 
La quantità totale di dati inviati dall'installazione.



 a| 
storagegrid_node_cpu_utilization_percent
 a| 
La percentuale di tempo CPU disponibile attualmente utilizzata da questo servizio. Indica la disponibilità del servizio. La quantità di tempo CPU disponibile dipende dal numero di CPU del server.



 a| 
storagegrid_ntp_chouged_time_source_offset_millisecondi
 a| 
Offset sistematico del tempo fornito da una fonte di tempo scelta. L'offset viene introdotto quando il ritardo per raggiungere un'origine temporale non è uguale al tempo richiesto per l'origine temporale per raggiungere il client NTP.



 a| 
storagegrid_ntp_locked
 a| 
Il nodo non è bloccato su un server NTP (Network Time Protocol).



 a| 
storagegrid_s3_data_transfers_bytes_ingested
 a| 
La quantità totale di dati acquisiti dai client S3 a questo nodo di storage dall'ultima reimpostazione dell'attributo.



 a| 
storagegrid_s3_data_transfers_bytes_retrieved
 a| 
La quantità totale di dati recuperati dai client S3 da questo nodo di storage dall'ultima reimpostazione dell'attributo.



 a| 
storagegrid_s3_operations_failed
 a| 
Il numero totale di operazioni S3 non riuscite (codici di stato HTTP 4xx e 5xx), escluse quelle causate da un errore di autorizzazione S3.



 a| 
storagegrid_s3_operations_successful
 a| 
Il numero totale di operazioni S3 riuscite (codice di stato HTTP 2xx).



 a| 
storagegrid_s3_operations_non autorizzato
 a| 
Il numero totale di operazioni S3 non riuscite che sono il risultato di un errore di autorizzazione.



 a| 
storagegrid_servercertificate_management_interface_cert_expiry_days
 a| 
Il numero di giorni prima della scadenza del certificato dell'interfaccia di gestione.



 a| 
storagegrid_servercertificate_storage_api_endpoints_cert_expiry_days
 a| 
Il numero di giorni prima della scadenza del certificato API dello storage a oggetti.



 a| 
storagegrid_service_cpu_seconds
 a| 
La quantità di tempo cumulativa in cui la CPU è stata utilizzata da questo servizio dopo l'installazione.



 a| 
storagegrid_service_memory_usage_bytes
 a| 
La quantità di memoria (RAM) attualmente utilizzata da questo servizio. Questo valore è identico a quello visualizzato dall'utility principale di Linux come RES.



 a| 
storagegrid_service_network_received_bytes
 a| 
La quantità totale di dati ricevuti dal servizio dopo l'installazione.



 a| 
storagegrid_service_network_transmitted_bytes
 a| 
La quantità totale di dati inviati da questo servizio.



 a| 
storagegrid_service_reavvies
 a| 
Il numero totale di riavvii del servizio.



 a| 
storagegrid_service_runtime_seconds
 a| 
Il tempo totale di esecuzione del servizio dopo l'installazione.



 a| 
storagegrid_service_uptime_seconds
 a| 
Il tempo totale di esecuzione del servizio dall'ultimo riavvio.



 a| 
storagegrid_storage_state_current
 a| 
Lo stato corrente dei servizi di storage. I valori degli attributi sono:

* 10 = non in linea
* 15 = manutenzione
* 20 = sola lettura
* 30 = Online




 a| 
storagegrid_storage_status
 a| 
Lo stato corrente dei servizi di storage. I valori degli attributi sono:

* 0 = Nessun errore
* 10 = in transizione
* 20 = spazio libero insufficiente
* 30 = Volume(i) non disponibile
* 40 = errore




 a| 
storagegrid_storage_utilization_bytes
 a| 
Una stima della dimensione totale dei dati degli oggetti replicati ed erasure coded sul nodo di storage.



 a| 
storagegrid_storage_utilization_metadata_allowed_bytes
 a| 
Lo spazio totale sul volume 0 di ciascun nodo di storage consentito per i metadati dell'oggetto. Questo valore è sempre inferiore allo spazio effettivo riservato ai metadati su un nodo, perché una parte dello spazio riservato è necessaria per le operazioni essenziali del database (come la compattazione e la riparazione) e i futuri aggiornamenti hardware e software. Lo spazio consentito per i metadati dell'oggetto controlla la capacità complessiva degli oggetti.



 a| 
storagegrid_storage_utilization_metadata_bytes
 a| 
La quantità di metadati oggetto sul volume di storage 0, in byte.



 a| 
storagegrid_storage_utilization_total_space_bytes
 a| 
La quantità totale di spazio di storage allocato a tutti gli archivi di oggetti.



 a| 
storagegrid_storage_utilization_usable_space_bytes
 a| 
La quantità totale di spazio di storage a oggetti rimanente. Calcolato sommando la quantità di spazio disponibile per tutti gli archivi di oggetti sul nodo di storage.



 a| 
storagegrid_swift_data_transfers_bytes_ingested
 a| 
La quantità totale di dati acquisiti dai client Swift a questo nodo di storage dall'ultima reimpostazione dell'attributo.



 a| 
storagegrid_swift_data_transfers_bytes_retrieved
 a| 
La quantità totale di dati recuperati dai client Swift da questo nodo di storage dall'ultima reimpostazione dell'attributo.



 a| 
storagegrid_swift_operations_failed
 a| 
Il numero totale di operazioni Swift non riuscite (codici di stato HTTP 4xx e 5xx), escluse quelle causate da un errore di autorizzazione Swift.



 a| 
storagegrid_swift_operations_successful
 a| 
Il numero totale di operazioni Swift riuscite (codice di stato HTTP 2xx).



 a| 
storagegrid_swift_operations_inhautorizzata
 a| 
Il numero totale di operazioni Swift non riuscite che sono il risultato di un errore di autorizzazione (codici di stato HTTP 401, 403, 405).



 a| 
storagegrid_tenant_usage_data_bytes
 a| 
La dimensione logica di tutti gli oggetti per il tenant.



 a| 
storagegrid_tenant_usage_object_count
 a| 
Il numero di oggetti per il tenant.



 a| 
storagegrid_tenant_usage_quota_byte
 a| 
La quantità massima di spazio logico disponibile per gli oggetti del tenant. Se non viene fornita una metrica di quota, è disponibile una quantità illimitata di spazio.

|===