---
permalink: maintain/all-node-types-replacing-vmware-node.html 
sidebar: sidebar 
keywords: replace VMware node 
summary: Quando si ripristina un nodo StorageGRID guasto ospitato su VMware, è necessario rimuovere il nodo guasto e implementare un nodo di ripristino. 
---
= Tutti i tipi di nodi grid: Sostituire il nodo VMware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si ripristina un nodo StorageGRID guasto ospitato su VMware, è necessario rimuovere il nodo guasto e implementare un nodo di ripristino.

.Di cosa hai bisogno
È necessario aver determinato che la macchina virtuale non può essere ripristinata e deve essere sostituita.

.A proposito di questa attività
VMware vSphere Web Client viene utilizzato per rimuovere prima la macchina virtuale associata al nodo Grid guasto. Quindi, è possibile implementare una nuova macchina virtuale.

Questa procedura è solo una fase del processo di ripristino del nodo grid. La procedura di rimozione e implementazione dei nodi è la stessa per tutti i nodi VMware, inclusi i nodi Admin, i nodi Storage, i nodi Gateway e i nodi Archive.

.Fasi
. Accedere a VMware vSphere Web Client.
. Passare alla macchina virtuale del nodo della griglia guasto.
. Prendere nota di tutte le informazioni necessarie per implementare il nodo di ripristino.
+
.. Fare clic con il pulsante destro del mouse sulla macchina virtuale, selezionare la scheda *Edit Settings* (Modifica impostazioni) e annotare le impostazioni in uso.
.. Selezionare la scheda *vApp Options* per visualizzare e registrare le impostazioni di rete del nodo della griglia.


. Se il nodo Grid guasto è un nodo Storage, determinare se uno dei dischi rigidi virtuali utilizzati per lo storage dei dati non è danneggiato e conservarlo per il ricollegamento al nodo Grid ripristinato.
. Spegnere la macchina virtuale.
. Selezionare *azioni* > *tutte le azioni vCenter* > *Elimina dal disco* per eliminare la macchina virtuale.
. Implementare una nuova macchina virtuale come nodo sostitutivo e connetterla a una o più reti StorageGRID.
+
Quando si implementa il nodo, è possibile rimappare le porte del nodo o aumentare le impostazioni della CPU o della memoria.

+

NOTE: Dopo aver implementato il nuovo nodo, è possibile aggiungere nuovi dischi virtuali in base ai requisiti di storage, ricollegare eventuali dischi rigidi virtuali conservati dal nodo Grid guasto precedentemente rimosso o da entrambi.

+
Per istruzioni:

+
xref:../vmware/index.adoc[Installare VMware] > implementazione di un nodo StorageGRID come macchina virtuale

. Completare la procedura di ripristino del nodo, in base al tipo di nodo che si sta ripristinando.
+
[cols="1a,2a"]
|===
| Tipo di nodo | Passare a. 


 a| 
Nodo amministratore primario
 a| 
xref:configuring-replacement-primary-admin-node.adoc[Configurare il nodo amministrativo primario sostitutivo]



 a| 
Nodo amministrativo non primario
 a| 
xref:selecting-start-recovery-to-configure-non-primary-admin-node.adoc[Selezionare Avvia ripristino per configurare il nodo di amministrazione non primario]



 a| 
Nodo gateway
 a| 
xref:selecting-start-recovery-to-configure-gateway-node.adoc[Selezionare Avvia ripristino per configurare il nodo gateway]



 a| 
Nodo di storage
 a| 
xref:selecting-start-recovery-to-configure-storage-node.adoc[Selezionare Avvia ripristino per configurare il nodo di storage]



 a| 
Nodo di archiviazione
 a| 
xref:selecting-start-recovery-to-configure-archive-node.adoc[Selezionare Start Recovery (Avvia ripristino) per configurare il nodo di archiviazione]

|===

