---
permalink: maintain/downloading-hotfix-file.html 
sidebar: sidebar 
keywords: storagegrid, hotfix, download 
summary: Prima di applicare la correzione rapida, è necessario scaricare il file della correzione rapida. 
---
= Scaricare il file hotfix
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di applicare la correzione rapida, è necessario scaricare il file della correzione rapida.

.Fasi
. Vai alla pagina dei download NetApp per StorageGRID.
+
https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["Download NetApp: StorageGRID"]

. Selezionare la freccia verso il basso sotto *Software disponibile* per visualizzare un elenco di hotfix disponibili per il download.
+

NOTE: Le versioni dei file hotfix hanno il formato: 11.4__.x.y__.

. Esaminare le modifiche incluse nell'aggiornamento.
+

NOTE: Se è stato appena ripristinato il nodo di amministrazione primario ed è necessario applicare una correzione rapida, selezionare la stessa versione della correzione rapida installata sugli altri nodi della griglia.

+
.. Selezionare la versione della correzione rapida che si desidera scaricare e selezionare *Go*.
.. Accedi utilizzando il nome utente e la password del tuo account NetApp.
.. Leggere e accettare il Contratto di licenza con l'utente finale.
+
Viene visualizzata la pagina di download della versione selezionata.

.. Scaricare la correzione rapida `readme.txt` file per visualizzare un riepilogo delle modifiche incluse nella correzione rapida.


. Selezionare il pulsante di download per la correzione rapida e salvare il file.
+

NOTE: Non modificare il nome del file.

+

NOTE: Se si utilizza un dispositivo macOS, il file hotfix potrebbe essere salvato automaticamente come `.txt` file. In tal caso, è necessario rinominare il file senza `.txt` interno.

. Selezionare una posizione per il download e selezionare *Salva*.


.Informazioni correlate
xref:configuring-replacement-primary-admin-node.adoc[Configurare il nodo amministrativo primario sostitutivo]
