---
permalink: maintain/downloading-recovery-package.html 
sidebar: sidebar 
keywords: storagegrid, recovery package 
summary: Il file del pacchetto di ripristino consente di ripristinare il sistema StorageGRID in caso di errore. 
---
= Scarica Recovery Package
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il file del pacchetto di ripristino consente di ripristinare il sistema StorageGRID in caso di errore.

.Di cosa hai bisogno
* È necessario accedere a Grid Manager utilizzando un xref:../admin/web-browser-requirements.adoc[browser web supportato].
* È necessario disporre della passphrase di provisioning.
* È necessario disporre di autorizzazioni di accesso specifiche.


Scaricare il file del pacchetto di ripristino corrente prima di apportare modifiche alla topologia della griglia al sistema StorageGRID o prima di aggiornare il software. Quindi, scaricare una nuova copia del pacchetto di ripristino dopo aver apportato modifiche alla topologia della griglia o dopo aver aggiornato il software.

.Fasi
. Selezionare *MANUTENZIONE* *sistema* *pacchetto di ripristino*.
. Inserire la passphrase di provisioning e selezionare *Avvia download*.
+
Il download viene avviato immediatamente.

. Al termine del download:
+
.. Aprire `.zip` file.
.. Confermare che includa una directory di backup gpt e una interna `.zip` file.
.. Estrarre l'interno `.zip` file.
.. Confermare che è possibile aprire `Passwords.txt` file.


. Copiare il file del pacchetto di ripristino scaricato (`.zip`) in due posizioni sicure e separate.
+

IMPORTANT: Il file del pacchetto di ripristino deve essere protetto perché contiene chiavi di crittografia e password che possono essere utilizzate per ottenere dati dal sistema StorageGRID.



.Informazioni correlate
xref:../admin/index.adoc[Amministrare StorageGRID]
