---
permalink: maintain/recovering-failed-storage-volumes-and-rebuilding-cassandra-database.html 
sidebar: sidebar 
keywords: storagegrid, recover, maintenance, maintain, failed storage volumes, failed volumes, cassandra, cassandra rebuild, rebuild cassandra, cassandra database 
summary: È necessario eseguire uno script che riformatta e rimontana lo storage su volumi di storage guasti e ricostruisce il database Cassandra sul nodo di storage, se il sistema lo ritiene necessario. 
---
= Ripristinare i volumi di storage guasti e ricostruire il database Cassandra
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario eseguire uno script che riformatta e rimontana lo storage su volumi di storage guasti e ricostruisce il database Cassandra sul nodo di storage, se il sistema lo ritiene necessario.

* È necessario disporre di `Passwords.txt` file.
* I dischi di sistema sul server devono essere intatti.
* La causa del guasto deve essere stata identificata e, se necessario, l'hardware di storage sostitutivo deve essere già stato acquistato.
* La dimensione totale dello storage sostitutivo deve essere uguale a quella dell'originale.
* È stato verificato che non è in corso la decommissionamento di un nodo di storage oppure che la procedura di decommissionamento del nodo è stata sospesa. (In Grid Manager, selezionare *MANUTENZIONE* > *attività* > *smantellamento*).
* Hai verificato che non è in corso un'espansione. (In Grid Manager, selezionare *MANUTENZIONE* > *attività* > *espansione*).
* Lo hai fatto xref:reviewing-warnings-about-storage-volume-recovery.adoc[analisi degli avvisi relativi al ripristino del volume di storage].
+
.. Se necessario, sostituire lo storage fisico o virtuale guasto associato ai volumi di storage guasti identificati e non montati in precedenza.
+
Dopo aver sostituito lo storage, assicurarsi di eseguire nuovamente la scansione o il riavvio per assicurarsi che sia riconosciuto dal sistema operativo, ma non rimontare i volumi. Lo storage viene rimontato e aggiunto a. `/etc/fstab` in un passaggio successivo.

.. Accedere al nodo di storage guasto:
+
... Immettere il seguente comando: `ssh admin@_grid_node_IP_`
... Immettere la password elencata in `Passwords.txt` file.
... Immettere il seguente comando per passare a root: `su -`
... Immettere la password elencata in `Passwords.txt` file.




+
Una volta effettuato l'accesso come root, il prompt cambia da `$` a. `#`.

+
.. Utilizzare un editor di testo (vi o vim) per eliminare i volumi guasti da `/etc/fstab` quindi salvare il file.
+

NOTE: Commenti su un volume guasto in `/etc/fstab` file insufficiente. Il volume deve essere cancellato da `fstab` mentre il processo di ripristino verifica che tutte le linee in `fstab` il file corrisponde ai file system montati.

.. Riformattare eventuali volumi di storage guasti e ricostruire il database Cassandra, se necessario. Inserire: `reformat_storage_block_devices.rb`
+
*** Se i servizi di storage sono in esecuzione, viene richiesto di interromperli. Immettere: *Y*
*** Se necessario, viene richiesto di ricostruire il database Cassandra.
+
**** Esaminare gli avvisi. Se non sono applicabili, ricostruire il database Cassandra. Immettere: *Y*
**** Se più di un nodo di storage non è in linea o se un altro nodo di storage è stato ricostruito negli ultimi 15 giorni. Immettere: *N*
+
Lo script verrà chiuso senza ricostruire Cassandra. Contattare il supporto tecnico.



*** Per ogni disco rangedb sul nodo di storage, quando viene richiesto: `Reformat the rangedb drive _<name>_ (device _<major number>:<minor number>_)? [y/n]?`, immettere una delle seguenti risposte:
+
**** *y* per riformattare un disco con errori. In questo modo, il volume di storage viene riformattato e il volume di storage riformattato viene aggiunto a. `/etc/fstab` file.
**** *n* se il disco non contiene errori e non si desidera riformattarlo.
+

NOTE: Selezionando *n* si esce dallo script. Montare il disco (se si ritiene che i dati sul disco debbano essere conservati e il disco non è stato montato per errore) oppure rimuoverlo. Quindi, eseguire `reformat_storage_block_devices.rb` di nuovo comando.

+

NOTE: Alcune procedure di ripristino StorageGRID utilizzano Reaper gestire le riparazioni Cassandra. Le riparazioni vengono eseguite automaticamente non appena vengono avviati i servizi correlati o richiesti. Si potrebbe notare un output di script che menziona "`reaper`" o "`Cassandra repair`". Se viene visualizzato un messaggio di errore che indica che la riparazione non è riuscita, eseguire il comando indicato nel messaggio di errore.

+
Nel seguente esempio di output, il disco `/dev/sdf` Deve essere riformattato e Cassandra non ha bisogno di essere ricostruito:

+
[listing]
----
root@DC1-S1:~ # reformat_storage_block_devices.rb
Storage services must be stopped before running this script.
Stop storage services [y/N]? **y**
Shutting down storage services.
Storage services stopped.
Formatting devices that are not in use...
Skipping in use device /dev/sdc
Skipping in use device /dev/sdd
Skipping in use device /dev/sde
Reformat the rangedb drive /dev/sdf (device 8:64)? [Y/n]? **y**
Successfully formatted /dev/sdf with UUID c817f87f-f989-4a21-8f03-b6f42180063f
Skipping in use device /dev/sdg
All devices processed
Running: /usr/local/ldr/setup_rangedb.sh 12075630
Cassandra does not need rebuilding.
Starting services.

Reformatting done.  Now do manual steps to
restore copies of data.
----







