---
permalink: maintain/reviewing-warnings-for-system-drive-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recover, system drive warning, storage node 
summary: Prima di ripristinare un disco di sistema guasto di un nodo di storage, è necessario esaminare i seguenti avvisi. 
---
= Esaminare gli avvisi per il ripristino del disco di sistema Storage Node
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di ripristinare un disco di sistema guasto di un nodo di storage, è necessario esaminare i seguenti avvisi.

I nodi di storage dispongono di un database Cassandra che include metadati a oggetti. Il database Cassandra potrebbe essere ricostruito nei seguenti casi:

* Un nodo di storage viene riportato online dopo essere stato offline per più di 15 giorni.
* Un volume di storage ha subito un errore e è stato ripristinato.
* Il disco di sistema e uno o più volumi di storage si guastano e vengono ripristinati.


Quando Cassandra viene ricostruita, il sistema utilizza le informazioni provenienti da altri nodi di storage. Se troppi nodi di storage sono offline, alcuni dati Cassandra potrebbero non essere disponibili. Se Cassandra è stata ricostruita di recente, i dati Cassandra potrebbero non essere ancora coerenti in tutta la griglia. La perdita di dati può verificarsi se Cassandra viene ricostruita quando troppi nodi di storage sono offline o se due o più nodi di storage vengono ricostruiti entro 15 giorni l'uno dall'altro.


CAUTION: Se più di un nodo di storage si è guastato (o non è in linea), contattare il supporto tecnico. Non eseguire la seguente procedura di ripristino. Potrebbe verificarsi una perdita di dati.


CAUTION: Se si tratta del secondo guasto del nodo di storage in meno di 15 giorni dopo un guasto o un ripristino del nodo di storage, contattare il supporto tecnico. La ricostruzione di Cassandra su due o più nodi di storage entro 15 giorni può causare la perdita di dati.


NOTE: Se più di un nodo di storage in un sito si è guastato, potrebbe essere necessaria una procedura di ripristino del sito. Contattare il supporto tecnico.

xref:how-site-recovery-is-performed-by-technical-support.adoc[Come viene eseguito il ripristino del sito dal supporto tecnico]


CAUTION: Se questo nodo di storage è in modalità di manutenzione in sola lettura per consentire il recupero di oggetti da parte di un altro nodo di storage con volumi di storage guasti, ripristinare i volumi sul nodo di storage con volumi di storage guasti prima di ripristinare questo nodo di storage guasto. Consultare le istruzioni per il ripristino dalla perdita di volumi di storage in cui il disco di sistema è intatto.


IMPORTANT: Se le regole ILM sono configurate in modo da memorizzare una sola copia replicata e la copia esiste su un volume di storage che ha avuto esito negativo, non sarà possibile ripristinare l'oggetto.


NOTE: Se si verifica un allarme Services: Status - Cassandra (SVST) durante il ripristino, consultare le istruzioni per il monitoraggio e la risoluzione dei problemi per ripristinare l'allarme mediante la ricostruzione di Cassandra. Dopo la ricostruzione di Cassandra, gli allarmi devono essere disattivati. Se gli allarmi non vengono disattivati, contattare il supporto tecnico.

.Informazioni correlate
xref:../monitor/index.adoc[Monitorare e risolvere i problemi]

xref:warnings-and-considerations-for-grid-node-recovery.adoc[Avvertenze e considerazioni per il ripristino del nodo grid]

xref:recovering-from-storage-volume-failure-where-system-drive-is-intact.adoc[Ripristino in seguito a un errore del volume di storage in cui il disco di sistema è intatto]
