---
permalink: primer/managing-tenants-and-client-connections.html 
sidebar: sidebar 
keywords: tenant, client, connect, connection 
summary: In qualità di amministratore di grid, è possibile creare e gestire gli account tenant utilizzati dai client S3 e Swift per memorizzare e recuperare gli oggetti e gestire le opzioni di configurazione che controllano il modo in cui i client si connettono al sistema StorageGRID. 
---
= Gestire tenant e connessioni client
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In qualità di amministratore di grid, è possibile creare e gestire gli account tenant utilizzati dai client S3 e Swift per memorizzare e recuperare gli oggetti e gestire le opzioni di configurazione che controllano il modo in cui i client si connettono al sistema StorageGRID.



== Account tenant

Un account tenant consente di specificare chi può utilizzare il sistema StorageGRID per memorizzare e recuperare gli oggetti e quali funzionalità sono disponibili. Gli account tenant consentono alle applicazioni client che supportano l'API REST S3 o l'API REST Swift di memorizzare e recuperare oggetti su StorageGRID. Ogni account tenant utilizza il protocollo client S3 o il protocollo client Swift.

È necessario creare almeno un account tenant per ogni protocollo client che verrà utilizzato per memorizzare gli oggetti nel sistema StorageGRID. Se si desidera separare gli oggetti memorizzati nel sistema da diverse entità, è possibile creare ulteriori account tenant. Ogni account tenant dispone di gruppi e utenti federati o locali e di bucket (container per Swift) e oggetti propri.

È possibile utilizzare Grid Manager o l'API Grid Management per creare account tenant. Quando si crea un account tenant, si specificano le seguenti informazioni:

* Nome visualizzato per il tenant (l'ID account del tenant viene assegnato automaticamente e non può essere modificato).
* Se l'account tenant utilizzerà S3 o Swift.
* Per gli account tenant S3: Se l'account tenant è autorizzato a utilizzare i servizi della piattaforma. Se è consentito l'utilizzo dei servizi della piattaforma, la griglia deve essere configurata per supportarne l'utilizzo.
* Facoltativamente, una quota di storage per l'account tenant, ovvero il numero massimo di gigabyte, terabyte o petabyte disponibili per gli oggetti del tenant. La quota di storage di un tenant rappresenta una quantità logica (dimensione dell'oggetto), non una quantità fisica (dimensione sul disco).
* Se la federazione delle identità è attivata per il sistema StorageGRID, il gruppo federato dispone dell'autorizzazione di accesso root per configurare l'account tenant.
* Se l'SSO (Single Sign-on) non è in uso per il sistema StorageGRID, se l'account tenant utilizzerà la propria origine di identità o condividerà l'origine di identità della griglia e la password iniziale per l'utente root locale del tenant.


Se gli account tenant S3 devono soddisfare i requisiti normativi, gli amministratori della griglia possono attivare l'impostazione globale S3 Object Lock per il sistema StorageGRID. Quando S3 Object Lock è attivato per il sistema, tutti gli account tenant S3 possono creare bucket con S3 Object Lock attivato e specificare le impostazioni di conservazione e conservazione legale per le versioni degli oggetti in quel bucket.

Una volta creato un account tenant, gli utenti tenant possono accedere al tenant manager.



== Connessioni client ai nodi StorageGRID

Prima che gli utenti tenant possano utilizzare i client S3 o Swift per memorizzare e recuperare i dati in StorageGRID, è necessario decidere come questi client si connetteranno ai nodi StorageGRID.

Le applicazioni client possono memorizzare o recuperare oggetti connettendosi a una delle seguenti opzioni:

* Il servizio Load Balancer sui nodi Admin o Gateway. Questa è la connessione consigliata.
* Il servizio CLB sui nodi gateway.
+

NOTE: Il servizio CLB è obsoleto.

* Nodi di storage, con o senza bilanciamento del carico esterno.


Quando si configura StorageGRID in modo che i client possano utilizzare il servizio bilanciamento del carico, attenersi alla seguente procedura:

. Configurare facoltativamente i gruppi ad alta disponibilità (ha). Se si crea un gruppo ha, le interfacce di più nodi Admin e nodi Gateway vengono inserite in una configurazione di backup attivo. Le connessioni client vengono effettuate utilizzando l'indirizzo IP virtuale del gruppo ha.
. Configurare gli endpoint per il servizio Load Balancer. Il servizio Load Balancer sui nodi di amministrazione o gateway distribuisce le connessioni di rete in entrata dalle applicazioni client ai nodi di storage. Quando si crea un endpoint di bilanciamento del carico, specificare un numero di porta, se l'endpoint accetta connessioni HTTP o HTTPS, il tipo di client (S3 o Swift) che utilizzerà l'endpoint e il certificato da utilizzare per le connessioni HTTPS (se applicabile).
. Facoltativamente, specificare che la rete client di un nodo non è attendibile per garantire che tutte le connessioni alla rete client del nodo si verifichino sugli endpoint del bilanciamento del carico.


.Informazioni correlate
* xref:../admin/index.adoc[Amministrare StorageGRID]
* xref:../tenant/index.adoc[Utilizzare un account tenant]
* xref:../s3/index.adoc[Utilizzare S3]
* xref:../swift/index.adoc[USA Swift]
* xref:exploring-tenant-manager.adoc[Esplora il tenant manager]
* xref:configuring-network-settings.adoc[Configurare le impostazioni di rete]

