---
permalink: sg5700/configuring-storagegrid-connections.html 
sidebar: sidebar 
keywords: storagegrid, sg5700, storage node, storage appliance, storagegrid connections, connections, configure, setup, set up 
summary: 'Prima di implementare un"appliance StorageGRID come nodo di storage in una griglia StorageGRID, è necessario configurare le connessioni tra l"appliance e le reti che si intende utilizzare. È possibile configurare la rete consultando il programma di installazione dell"appliance StorageGRID, incluso nel controller E5700SG (il controller di calcolo dell"appliance).' 
---
= Configurazione delle connessioni StorageGRID (SG5700)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di implementare un'appliance StorageGRID come nodo di storage in una griglia StorageGRID, è necessario configurare le connessioni tra l'appliance e le reti che si intende utilizzare. È possibile configurare la rete consultando il programma di installazione dell'appliance StorageGRID, incluso nel controller E5700SG (il controller di calcolo dell'appliance).

.Fasi
* xref:accessing-storagegrid-appliance-installer-sg5700.adoc[Accedere al programma di installazione dell'appliance StorageGRID]
* xref:verifying-and-upgrading-storagegrid-appliance-installer-version.adoc[Verificare e aggiornare la versione del programma di installazione dell'appliance StorageGRID]
* xref:configuring-network-links-sg5700.adoc[Configurazione dei collegamenti di rete (SG5700)]
* xref:setting-ip-configuration-sg5700.adoc[Impostare la configurazione IP]
* xref:verifying-network-connections.adoc[Verificare le connessioni di rete]
* xref:verifying-port-level-network-connections.adoc[Verificare le connessioni di rete a livello di porta]

