---
permalink: sg5700/hardware-setup-appears-to-hang.html 
sidebar: sidebar 
keywords: storagegrid, sg5700, storage node, storage appliance, troubleshoot, troubleshooting, hardware, setup, hang, hangs, fails, failure, stop, terminate, terminates, stuck 
summary: 'Il programma di installazione dell"appliance StorageGRID potrebbe non essere disponibile se errori hardware o di cablaggio impediscono al controller E5700SG di completare l"elaborazione di avvio.' 
---
= La configurazione dell'hardware sembra bloccarsi (SG5700)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il programma di installazione dell'appliance StorageGRID potrebbe non essere disponibile se errori hardware o di cablaggio impediscono al controller E5700SG di completare l'elaborazione di avvio.

.Fasi
. Osservare i codici sui display a sette segmenti.
+
Durante l'inizializzazione dell'hardware durante l'accensione, i due display a sette segmenti mostrano una sequenza di codici. Quando l'hardware viene avviato correttamente, i display a sette segmenti mostrano codici diversi per ciascun controller.

. Esaminare i codici sul display a sette segmenti della centralina E5700SG.
+

NOTE: L'installazione e il provisioning richiedono tempo. Alcune fasi di installazione non riportano gli aggiornamenti al programma di installazione dell'appliance StorageGRID per alcuni minuti.

+
Se si verifica un errore, il display a sette segmenti fa lampeggiare una sequenza, ad esempio HE.

. Per comprendere il significato di questi codici, consulta le seguenti risorse:
+
|===
| Controller | Riferimento 


 a| 
Controller E5700SG
 a| 
** "`sindicatori di stato sul controller E5700SG`"
** "`errore: Errore di sincronizzazione con il software SANtricity OS`"




 a| 
Controller E2800
 a| 
_Guida al monitoraggio dei sistemi E5700 e E2800_

*Nota:* i codici descritti per il controller e-Series E5700 non si applicano al controller E5700SG dell'appliance.

|===
. Se il problema persiste, contattare il supporto tecnico.


.Informazioni correlate
xref:status-indicators-on-e5700sg-controller.adoc[Indicatori di stato sul controller E5700SG]

xref:he-error-error-synchronizing-with-santricity-os-software.adoc[ERRORE HE: Errore di sincronizzazione con il software SANtricity OS]

http://mysupport.netapp.com/info/web/ECMP1658252.html["Sito di documentazione dei sistemi NetApp e-Series"^]
