---
permalink: sg5700/optional-changing-raid-mode-sg5760-only.html 
sidebar: sidebar 
keywords: storagegrid, sg5700, storage node, storage appliance, raid, raid mode, change, changing, modify, DDP, ddp16, raid6 
summary: 'Se si dispone di un sistema SG5760 con 60 dischi, è possibile passare a una modalità RAID diversa per soddisfare i requisiti di storage e ripristino. È possibile modificare la modalità solo prima di implementare il nodo di storage dell"appliance StorageGRID.' 
---
= Opzionale: Modifica della modalità RAID (solo SG5760)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si dispone di un sistema SG5760 con 60 dischi, è possibile passare a una modalità RAID diversa per soddisfare i requisiti di storage e ripristino. È possibile modificare la modalità solo prima di implementare il nodo di storage dell'appliance StorageGRID.

.Di cosa hai bisogno
* Hai un SG5760. Se si dispone di un SG5712, è necessario utilizzare la modalità DDP.
* Si sta utilizzando qualsiasi client in grado di connettersi a StorageGRID.
* Il client dispone di un xref:../admin/web-browser-requirements.adoc[browser web supportato].


.A proposito di questa attività
Prima di implementare l'appliance SG5760 come nodo di storage, è possibile scegliere una delle seguenti opzioni di configurazione del volume:

* *DDP*: Questa modalità utilizza due unità di parità ogni otto unità dati. Questa è la modalità predefinita e consigliata per tutti gli appliance. Rispetto a RAID6, DDP offre migliori prestazioni di sistema, tempi di ricostruzione ridotti dopo guasti al disco e facilità di gestione. DDP offre anche la protezione contro le perdite di cassetto nelle appliance a 60 dischi.
* *DDP16*: Questa modalità utilizza due unità di parità ogni 16 unità dati, il che comporta una maggiore efficienza dello storage rispetto al DDP. Rispetto a RAID6, il sistema DDP16 offre migliori performance di sistema, tempi di ricostruzione ridotti dopo guasti del disco, facilità di gestione ed efficienza dello storage paragonabile. Per utilizzare la modalità DDP16, la configurazione deve contenere almeno 20 dischi. Il DDP16 non fornisce la protezione contro le perdite di cassetto.
* *RAID6*: Questa modalità utilizza due unità di parità per ogni 16 o più unità dati. Per utilizzare la modalità RAID 6, la configurazione deve contenere almeno 20 dischi. Sebbene RAID6 possa aumentare l'efficienza dello storage dell'appliance rispetto a DDP, non è consigliato per la maggior parte degli ambienti StorageGRID.



IMPORTANT: Se alcuni volumi sono già stati configurati o se StorageGRID è stato installato in precedenza, la modifica della modalità RAID comporta la rimozione e la sostituzione dei volumi. Tutti i dati presenti su tali volumi andranno persi.

.Fasi
. Utilizzando il laptop di assistenza, aprire un browser Web e accedere al programma di installazione dell'appliance StorageGRID: +
`*https://_E5700SG_Controller_IP_:8443*`
+
Dove `_E5700SG_Controller_IP_` Indica uno degli indirizzi IP del controller E5700SG.

. Selezionare *Advanced* (Avanzate) > *RAID Mode* (modalità RAID).
. Nella pagina *Configure RAID Mode* (Configura modalità RAID), selezionare la modalità RAID desiderata dall'elenco a discesa Mode (modalità).
. Fare clic su *Save* (Salva).


.Informazioni correlate
http://mysupport.netapp.com/info/web/ECMP1658252.html["Sito di documentazione dei sistemi NetApp e-Series"^]
