---
permalink: sg5700/overview-of-installation-rest-apis.html 
sidebar: sidebar 
keywords: storagegrid, sg5700, storage node, storage appliance, installation REST API, REST API, installation REST APIs, REST APIs, Appliance Installer API, Appliance Installer APIs, Install API, Install APIs, Installer API, Installer APIs, Installation API, Installation APIs, api, apis 
summary: 'StorageGRID fornisce due API REST per eseguire le attività di installazione: L"API di installazione di StorageGRID e l"API di installazione di appliance StorageGRID.' 
---
= Panoramica delle API REST di installazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID fornisce due API REST per eseguire le attività di installazione: L'API di installazione di StorageGRID e l'API di installazione di appliance StorageGRID.

Entrambe le API utilizzano la piattaforma API open source Swagger per fornire la documentazione API. Swagger consente agli sviluppatori e ai non sviluppatori di interagire con l'API in un'interfaccia utente che illustra il modo in cui l'API risponde a parametri e opzioni. Questa documentazione presuppone che l'utente abbia familiarità con le tecnologie Web standard e con il formato dati JSON (JavaScript Object Notation).


IMPORTANT: Tutte le operazioni API eseguite utilizzando la pagina web API Docs sono operazioni live. Fare attenzione a non creare, aggiornare o eliminare per errore i dati di configurazione o altri dati.

Ogni comando REST API include l'URL dell'API, un'azione HTTP, qualsiasi parametro URL richiesto o opzionale e una risposta API prevista.



== API di installazione StorageGRID

L'API di installazione di StorageGRID è disponibile solo quando si configura inizialmente il sistema StorageGRID e nel caso in cui sia necessario eseguire un ripristino primario del nodo di amministrazione. È possibile accedere all'API di installazione tramite HTTPS da Grid Manager.

Per accedere alla documentazione API, accedere alla pagina Web di installazione nel nodo di amministrazione principale e selezionare *Guida* > *documentazione API* dalla barra dei menu.

L'API di installazione di StorageGRID include le seguenti sezioni:

* *Config* -- operazioni relative alla release del prodotto e alle versioni dell'API. È possibile elencare la versione di release del prodotto e le principali versioni dell'API supportate da tale release.
* *Grid* -- operazioni di configurazione a livello di griglia. È possibile ottenere e aggiornare le impostazioni della griglia, inclusi i dettagli della griglia, le subnet Grid Network, le password della griglia e gli indirizzi IP dei server NTP e DNS.
* *NODI* -- operazioni di configurazione a livello di nodo. È possibile recuperare un elenco di nodi griglia, eliminare un nodo griglia, configurare un nodo griglia, visualizzare un nodo griglia e ripristinare la configurazione di un nodo griglia.
* *Provision* -- operazioni di provisioning. È possibile avviare l'operazione di provisioning e visualizzare lo stato dell'operazione di provisioning.
* *Recovery* -- operazioni di recovery del nodo di amministrazione principale. È possibile ripristinare le informazioni, caricare il pacchetto di ripristino, avviare il ripristino e visualizzare lo stato dell'operazione di ripristino.
* *Recovery-package* -- operazioni per scaricare il pacchetto di ripristino.
* *Siti* -- operazioni di configurazione a livello di sito. È possibile creare, visualizzare, eliminare e modificare un sito.




== API di installazione dell'appliance StorageGRID

È possibile accedere all'API del programma di installazione dell'appliance StorageGRID tramite HTTPS da  `_Controller_IP_:8443`.

Per accedere alla documentazione API, accedere al programma di installazione dell'appliance StorageGRID e selezionare *Guida* > *documenti API* dalla barra dei menu.

L'API di installazione dell'appliance StorageGRID include le seguenti sezioni:

* *Clone* -- operazioni per configurare e controllare la clonazione del nodo.
* *Encryption* -- operazioni per gestire la crittografia e visualizzare lo stato della crittografia.
* *Configurazione hardware* -- operazioni per configurare le impostazioni di sistema sull'hardware collegato.
* *Installazione* -- operazioni per avviare l'installazione dell'appliance e monitorare lo stato dell'installazione.
* *Rete* -- operazioni correlate alla configurazione di rete, amministratore e client per un'appliance StorageGRID e le impostazioni delle porte dell'appliance.
* *Setup* -- operazioni utili per la configurazione iniziale dell'appliance, incluse richieste di informazioni sul sistema e aggiornamento dell'IP principale del nodo di amministrazione.
* *SUPPORT* -- operazioni per riavviare il controller e ottenere i log.
* *Upgrade* -- operazioni relative all'aggiornamento del firmware dell'appliance.
* *Uploadsg* -- operazioni per il caricamento dei file di installazione di StorageGRID.

