---
permalink: sg5700/preparing-site-sg5700.html 
sidebar: sidebar 
keywords: storagegrid, sg5700, storage node, storage appliance, install, installation, site prep, site preparating, preparing site, site requirements, requirements, site, dimensions, weight, weights, temperature, humidity, altitude, airflow, heat, wiring, power, grounding, facility 
summary: 'Prima di installare l"apparecchio, assicurarsi che il sito e l"armadietto o il rack che si intende utilizzare soddisfino le specifiche di un"appliance StorageGRID.' 
---
= Preparazione del sito (SG5700)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di installare l'apparecchio, assicurarsi che il sito e l'armadietto o il rack che si intende utilizzare soddisfino le specifiche di un'appliance StorageGRID.

.Fasi
. Verificare che il sito soddisfi i requisiti di temperatura, umidità, intervallo di altitudine, flusso d'aria, dissipazione del calore, cablaggio, alimentazione e messa a terra. Per ulteriori informazioni, consulta il NetApp Hardware Universe.
. Se si sta installando il modello SG5760, verificare che la propria posizione fornisca alimentazione CA a 240 volt.
. Procurarsi un cabinet da 19" (48.3 cm) o un rack per gli scaffali di queste dimensioni (senza cavi):
+
|===
| Modello di appliance | Altezza | Larghezza | Profondità | Peso massimo 


 a| 
SG5712

(12 dischi)
 a| 
3.41 poll.

(8.68 cm)
 a| 
17.6 poll.

(44.7 cm)
 a| 
21.1 poll.

(53.6 cm)
 a| 
63.9 libbre

(29.0 kg)



 a| 
SG5760

(60 dischi)
 a| 
6.87 poll.

(17.46 cm)
 a| 
17.66 poll.

(44.86 cm)
 a| 
38.25 poll.

(97.16 cm)
 a| 
250 libbre

(113 kg)

|===
. Installare gli switch di rete necessari. Per informazioni sulla compatibilità, consulta il tool NetApp Interoperability Matrix Tool.


.Informazioni correlate
https://hwu.netapp.com["NetApp Hardware Universe"^]

https://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità NetApp"^]
