---
permalink: ilm/guidelines-for-creating-storage-pools.html 
sidebar: sidebar 
keywords: storage pool guidelines 
summary: 'Per la configurazione e l"utilizzo dei pool di storage, attenersi alle seguenti linee guida.' 
---
= Linee guida per la creazione di pool di storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per la configurazione e l'utilizzo dei pool di storage, attenersi alle seguenti linee guida.



== Linee guida per tutti i pool di storage

* StorageGRID include un pool di storage predefinito, tutti i nodi di storage, che utilizza il sito predefinito, tutti i siti e il livello di storage predefinito, tutti i nodi di storage. Il pool di storage All Storage Node viene aggiornato automaticamente ogni volta che si aggiungono nuovi siti del data center.
+

NOTE: Si sconsiglia di utilizzare il pool di storage All Storage Node o il sito All Sites perché questi elementi vengono aggiornati automaticamente per includere i nuovi siti aggiunti in un'espansione, il che potrebbe non essere il comportamento desiderato. Prima di utilizzare il pool di storage All Storage Node o il sito predefinito, rivedere attentamente le linee guida per le copie replicate e codificate per l'erasure.

* Le configurazioni del pool di storage sono il più semplici possibile. Non creare più pool di storage del necessario.
* Creare pool di storage con il maggior numero possibile di nodi. Ogni pool di storage deve contenere due o più nodi. Un pool di storage con nodi insufficienti può causare backlog ILM se un nodo diventa non disponibile.
* Evitare di creare o utilizzare pool di storage che si sovrappongono (contenenti uno o più degli stessi nodi). Se i pool di storage si sovrappongono, è possibile che più di una copia dei dati dell'oggetto venga salvata sullo stesso nodo.




== Linee guida per i pool di storage utilizzati per le copie replicate

* Creare un pool di storage diverso per ciascun sito. Quindi, specificare uno o più pool di storage specifici del sito nelle istruzioni di posizionamento per ciascuna regola. L'utilizzo di un pool di storage per ciascun sito garantisce che le copie degli oggetti replicate vengano posizionate esattamente dove ci si aspetta (ad esempio, una copia di ogni oggetto in ogni sito per la protezione dalla perdita di sito).
* Se si aggiunge un sito in un'espansione, creare un nuovo pool di storage per il nuovo sito. Quindi, aggiornare le regole ILM per controllare quali oggetti sono memorizzati nel nuovo sito.
* In generale, non utilizzare il pool di storage predefinito, tutti i nodi di storage o qualsiasi pool di storage che includa il sito predefinito, tutti i siti.




== Linee guida per i pool di storage utilizzati per le copie erasure-coded

* Non è possibile utilizzare i nodi di archiviazione per i dati con codifica erasure.
* Il numero di nodi e siti di storage contenuti nel pool di storage determina quali schemi di erasure coding sono disponibili.
* Se un pool di storage include solo due siti, non è possibile utilizzare tale pool di storage per la cancellazione del codice. Non sono disponibili schemi di erasure coding per un pool di storage con due siti.
* In generale, non utilizzare il pool di storage predefinito, tutti i nodi di storage o qualsiasi pool di storage che includa il sito predefinito, tutti i siti in qualsiasi profilo di codifica Erasure.
+

NOTE: Se la griglia include un solo sito, non è possibile utilizzare il pool di storage All Storage Node o il sito predefinito All Sites in un profilo di codifica Erasure. Questo comportamento impedisce che il profilo di codifica Erasure diventi non valido se viene aggiunto un secondo sito.

* Se si hanno requisiti di throughput elevati, la creazione di un pool di storage che include più siti non è consigliata se la latenza di rete tra siti è superiore a 100 ms. Con l'aumentare della latenza, la velocità con cui StorageGRID può creare, posizionare e recuperare frammenti di oggetti diminuisce drasticamente a causa della diminuzione del throughput di rete TCP. La diminuzione del throughput influisce sui tassi massimi raggiungibili di acquisizione e recupero degli oggetti (quando si seleziona Strict o Balanced come comportamento Ingest) o può portare a backlog della coda ILM (quando viene selezionato Dual Commit come comportamento Ingest).
* Se possibile, un pool di storage deve includere un numero superiore al numero minimo di nodi di storage richiesto per lo schema di erasure coding selezionato. Ad esempio, se si utilizza uno schema di erasure coding 6+3, è necessario disporre di almeno nove nodi di storage. Tuttavia, si consiglia di disporre di almeno un nodo di storage aggiuntivo per sito.
* Distribuire i nodi di storage tra i siti nel modo più uniforme possibile. Ad esempio, per supportare uno schema di erasure coding 6+3, configurare un pool di storage che includa almeno tre nodi di storage in tre siti.




== Linee guida per i pool di storage utilizzati per le copie archiviate

* Non è possibile creare un pool di storage che includa nodi di storage e nodi di archiviazione. Le copie archiviate richiedono un pool di storage che includa solo i nodi di archiviazione.
* Quando si utilizza un pool di storage che include nodi di archiviazione, è necessario mantenere almeno una copia replicata o codificata in cancellazione su un pool di storage che include nodi di storage.
* Se l'impostazione blocco oggetti S3 globale è attivata e si sta creando una regola ILM conforme, non è possibile utilizzare un pool di storage che include nodi di archiviazione. Vedere le istruzioni per la gestione degli oggetti con S3 Object Lock.
* Se il tipo di destinazione di un nodo di archiviazione è Cloud Tiering - Simple Storage Service (S3), il nodo di archiviazione deve trovarsi nel proprio pool di storage. Vedere xref:../admin/index.adoc[Amministrare StorageGRID].


.Informazioni correlate
* xref:what-replication-is.adoc[Che cos'è la replica]
* xref:what-erasure-coding-is.adoc[Che cos'è la cancellazione dei codici]
* xref:what-erasure-coding-schemes-are.adoc[Quali sono gli schemi di erasure coding]
* xref:using-multiple-storage-pools-for-cross-site-replication.adoc[Utilizzo di più pool di storage per la replica tra siti]

