---
permalink: ilm/what-erasure-coding-schemes-are.html 
sidebar: sidebar 
keywords: erasure coding scheme 
summary: Quando si configura il profilo Erasure coding per una regola ILM, si seleziona uno schema di erasure coding disponibile in base al numero di nodi e siti di storage che si intende utilizzare nel pool di storage. Gli schemi di erasure coding controllano il numero di frammenti di dati e il numero di frammenti di parità creati per ciascun oggetto. 
---
= Quali sono gli schemi di erasure coding
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si configura il profilo Erasure coding per una regola ILM, si seleziona uno schema di erasure coding disponibile in base al numero di nodi e siti di storage che si intende utilizzare nel pool di storage. Gli schemi di erasure coding controllano il numero di frammenti di dati e il numero di frammenti di parità creati per ciascun oggetto.

Il sistema StorageGRID utilizza l'algoritmo di erasure coding Reed-Solomon. L'algoritmo suddivide un oggetto in k frammenti di dati e calcola m frammenti di parità. I frammenti k + m = n sono distribuiti su n nodi di storage per fornire protezione dei dati. Un oggetto può sostenere fino a m frammenti persi o corrotti. k frammenti sono necessari per recuperare o riparare un oggetto.

Quando si configura un profilo di codifica Erasure, attenersi alle seguenti linee guida per i pool di storage:

* Il pool di storage deve includere tre o più siti, o esattamente un sito.
+

NOTE: Non è possibile configurare un profilo di codifica Erasure se il pool di storage include due siti.

+
** <<Schemi di erasure coding per pool di storage contenenti tre o più siti,Schemi di erasure coding per pool di storage contenenti tre o più siti>>
** <<Schemi di erasure coding per pool di storage a sito singolo,Schemi di erasure coding per pool di storage a sito singolo>>


* Non utilizzare il pool di storage predefinito, tutti i nodi di storage o un pool di storage che include il sito predefinito, tutti i siti.
* Il pool di storage deve includere almeno _k+m_ +1 nodi di storage.
+
Il numero minimo di nodi di storage richiesto è _k+m_. Tuttavia, disporre di almeno un nodo di storage aggiuntivo può contribuire a prevenire gli errori di acquisizione o i backlog ILM se un nodo di storage richiesto non è temporaneamente disponibile.



L'overhead dello storage di uno schema di erasure coding viene calcolato dividendo il numero di frammenti di parità (_m_) per il numero di frammenti di dati (_k_). È possibile utilizzare l'overhead dello storage per calcolare la quantità di spazio su disco richiesta da ciascun oggetto con codifica di cancellazione:

`_disk space_ = _object size_ + (_object size_ * _storage overhead_)`

Ad esempio, se si memorizza un oggetto da 10 MB utilizzando lo schema 4+2 (con un overhead dello storage del 50%), l'oggetto consuma 15 MB di storage grid. Se si memorizza lo stesso oggetto da 10 MB utilizzando lo schema 6+2 (con un overhead dello storage del 33%), l'oggetto consuma circa 13.3 MB.

Seleziona lo schema di erasure coding con il valore totale più basso di _k+m_ che soddisfi le tue esigenze. gli schemi di erasure coding con un numero inferiore di frammenti sono in generale più efficienti dal punto di vista computazionale, in quanto vengono creati e distribuiti (o recuperati) meno frammenti per oggetto, possono mostrare performance migliori grazie alle maggiori dimensioni dei frammenti e possono richiedere l'aggiunta di un numero inferiore di nodi in un'espansione quando è necessario più storage. (Per informazioni sulla pianificazione di un'espansione dello storage, consultare le istruzioni relative all'espansione di StorageGRID).



== Schemi di erasure coding per pool di storage contenenti tre o più siti

La seguente tabella descrive gli schemi di erasure coding attualmente supportati da StorageGRID per i pool di storage che includono tre o più siti. Tutti questi schemi offrono la protezione contro le perdite di sito. È possibile perdere un sito e l'oggetto sarà ancora accessibile.

Per gli schemi di erasure coding che forniscono la protezione contro la perdita di sito, il numero consigliato di nodi di storage nel pool di storage supera _k+m_+1 perché ogni sito richiede un minimo di tre nodi di storage.

[cols="1a,1a,1a,1a,1a,1a"]
|===
| Schema di erasure coding (_k+m_) | Numero minimo di siti implementati | Numero consigliato di nodi di storage in ogni sito | Numero totale consigliato di nodi di storage | Protezione contro le perdite di sito? | Overhead dello storage 


 a| 
4+2
 a| 
3
 a| 
3
 a| 
9
 a| 
Sì
 a| 
50%



 a| 
6+2
 a| 
4
 a| 
3
 a| 
12
 a| 
Sì
 a| 
33%



 a| 
8+2
 a| 
5
 a| 
3
 a| 
15
 a| 
Sì
 a| 
25%



 a| 
6+3
 a| 
3
 a| 
4
 a| 
12
 a| 
Sì
 a| 
50%



 a| 
9+3
 a| 
4
 a| 
4
 a| 
16
 a| 
Sì
 a| 
33%



 a| 
2+1
 a| 
3
 a| 
3
 a| 
9
 a| 
Sì
 a| 
50%



 a| 
4+1
 a| 
5
 a| 
3
 a| 
15
 a| 
Sì
 a| 
25%



 a| 
6+1
 a| 
7
 a| 
3
 a| 
21
 a| 
Sì
 a| 
17%



 a| 
7+5
 a| 
3
 a| 
5
 a| 
15
 a| 
Sì
 a| 
71%

|===

NOTE: StorageGRID richiede un minimo di tre nodi di storage per sito. Per utilizzare lo schema 7+5, ogni sito richiede almeno quattro nodi di storage. Si consiglia di utilizzare cinque nodi di storage per sito.

Quando si seleziona uno schema di erasure coding che fornisce la protezione del sito, bilanciare l'importanza relativa dei seguenti fattori:

* *Numero di frammenti*: Le prestazioni e la flessibilità di espansione sono generalmente migliori quando il numero totale di frammenti è inferiore.
* *Fault tolerance*: La tolleranza di errore viene aumentata con più segmenti di parità (ovvero, quando _m_ ha un valore più elevato).
* *Traffico di rete*: Durante il ripristino da errori, l'utilizzo di uno schema con più frammenti (ovvero, un totale maggiore per _k+m_) crea più traffico di rete.
* *Overhead dello storage*: Gli schemi con overhead più elevato richiedono più spazio di storage per oggetto.


Ad esempio, quando si decide tra uno schema 4+2 e uno schema 6+3 (entrambi con un overhead dello storage del 50%), selezionare lo schema 6+3 se è richiesta una fault tolerance aggiuntiva. Selezionare lo schema 4+2 se le risorse di rete sono limitate. Se tutti gli altri fattori sono uguali, selezionare 4+2 perché il numero totale di frammenti è inferiore.


NOTE: In caso di dubbi sul programma da utilizzare, selezionare 4+2 o 6+3 oppure contattare il supporto tecnico.



== Schemi di erasure coding per pool di storage a sito singolo

Un pool di storage a sito singolo supporta tutti gli schemi di erasure coding definiti per tre o più siti, a condizione che il sito disponga di un numero sufficiente di nodi di storage.

Il numero minimo di nodi di storage richiesto è _k+m_, ma si consiglia un pool di storage con _k+m_+1 nodi di storage. Ad esempio, lo schema di erasure coding 2+1 richiede un pool di storage con almeno tre nodi di storage, ma si consiglia di utilizzare quattro nodi di storage.

[cols="1a,1a,1a,1a"]
|===
| Schema di erasure coding (_k+m_) | Numero minimo di nodi di storage | Numero consigliato di nodi di storage | Overhead dello storage 


 a| 
4+2
 a| 
6
 a| 
7
 a| 
50%



 a| 
6+2
 a| 
8
 a| 
9
 a| 
33%



 a| 
8+2
 a| 
10
 a| 
11
 a| 
25%



 a| 
6+3
 a| 
9
 a| 
10
 a| 
50%



 a| 
9+3
 a| 
12
 a| 
13
 a| 
33%



 a| 
2+1
 a| 
3
 a| 
4
 a| 
50%



 a| 
4+1
 a| 
5
 a| 
6
 a| 
25%



 a| 
6+1
 a| 
7
 a| 
8
 a| 
17%



 a| 
7+5
 a| 
12
 a| 
13
 a| 
71%

|===
.Informazioni correlate
xref:../expand/index.adoc[Espandi il tuo grid]
