---
permalink: ilm/what-storage-pool-is.html 
sidebar: sidebar 
keywords: what is a storage pool 
summary: Un pool di storage è un raggruppamento logico di nodi di storage o nodi di archivio. I pool di storage vengono configurati per determinare dove il sistema StorageGRID memorizza i dati a oggetti e il tipo di storage utilizzato. 
---
= Che cos'è un pool di storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un pool di storage è un raggruppamento logico di nodi di storage o nodi di archivio. I pool di storage vengono configurati per determinare dove il sistema StorageGRID memorizza i dati a oggetti e il tipo di storage utilizzato.

I pool di storage hanno due attributi:

* *Storage grade*: Per i nodi di storage, le performance relative dello storage di backup.
* *Sito*: Il data center in cui verranno memorizzati gli oggetti.


I pool di storage vengono utilizzati nelle regole ILM per determinare dove sono memorizzati i dati degli oggetti. Quando si configurano le regole ILM per la replica, si selezionano uno o più pool di storage che includono nodi di storage o nodi di archivio. Quando si creano profili di codifica Erasure, si seleziona un pool di storage che include i nodi di storage.
