---
permalink: fabricpool/creating-ha-group-for-fabricpool.html 
sidebar: sidebar 
keywords: fabricPool, high availability group, HA group, create, creating, virtual IP, VIP, preferred master, backup interface 
summary: 'Quando si configura StorageGRID per l"utilizzo con FabricPool, è possibile creare facoltativamente uno o più gruppi ad alta disponibilità. Un gruppo ha è costituito da una o più interfacce di rete su nodi di amministrazione, nodi gateway o entrambi.' 
---
= Creare un gruppo ad alta disponibilità (ha) per FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si configura StorageGRID per l'utilizzo con FabricPool, è possibile creare facoltativamente uno o più gruppi ad alta disponibilità (ha). Un gruppo ha è costituito da una o più interfacce di rete su nodi di amministrazione, nodi gateway o entrambi.

.Di cosa hai bisogno
* Hai effettuato l'accesso a Grid Manager utilizzando un xref:../admin/web-browser-requirements.adoc[browser web supportato].
* Si dispone dell'autorizzazione di accesso root.
* Se si intende utilizzare una VLAN, è stata creata l'interfaccia VLAN. Vedere xref:../admin/configure-vlan-interfaces.adoc[Configurare le interfacce VLAN].


.A proposito di questa attività
Ogni gruppo ha utilizza indirizzi IP virtuali (VIP) per fornire un accesso altamente disponibile ai servizi condivisi sui nodi associati.

Per ulteriori informazioni su questa attività, vedere xref:../admin/managing-high-availability-groups.adoc[Gestire i gruppi ad alta disponibilità].

.Fasi
. Selezionare *CONFIGURATION* > *Network* > *High Availability groups*.
. Selezionare *Crea*.
. Immettere un nome univoco e, facoltativamente, una descrizione.
. Selezionare una o più interfacce da aggiungere a questo gruppo ha.
+
Utilizzare le intestazioni di colonna per ordinare le righe o inserire un termine di ricerca per individuare le interfacce più rapidamente.

. Determinare l'interfaccia primaria e le interfacce di backup per questo gruppo ha.
+
Trascinare e rilasciare le righe per modificare i valori nella colonna *Ordine di priorità*.

+
La prima interfaccia nell'elenco è l'interfaccia primaria. L'interfaccia principale è l'interfaccia attiva a meno che non si verifichi un errore.

+
Se il gruppo ha include più di un'interfaccia e l'interfaccia attiva non riesce, gli indirizzi VIP si spostano sulla prima interfaccia di backup nell'ordine di priorità. Se l'interfaccia non funziona, gli indirizzi VIP passano all'interfaccia di backup successiva e così via. Quando i guasti vengono risolti, gli indirizzi VIP tornano all'interfaccia con la priorità più alta disponibile.

. Specificare la subnet VIP nella notazione CIDR& 8212;un indirizzo IPv4 seguito da una barra e dalla lunghezza della subnet (0-32).
+
L'indirizzo di rete non deve avere bit host impostati. Ad esempio, `192.16.0.0/22`.

. Se si desidera, gli indirizzi IP ONTAP utilizzati per accedere a StorageGRID non si trovano sulla stessa sottorete degli indirizzi VIP StorageGRID, immettere l'indirizzo IP del gateway locale VIP StorageGRID. L'indirizzo IP del gateway locale deve trovarsi all'interno della subnet VIP.
. Inserire uno o più indirizzi IP virtuali per il gruppo ha. È possibile aggiungere fino a 10 indirizzi IP. Tutti i VIP devono trovarsi all'interno della subnet VIP.
+
Specificare almeno un indirizzo IPv4. In alternativa, è possibile specificare ulteriori indirizzi IPv4 e IPv6.

. Selezionare *Create ha group* (Crea gruppo ha), quindi selezionare *Finish* (fine).

