---
permalink: fabricpool/other-best-practices-for-storagegrid-and-fabricpool.html 
sidebar: sidebar 
keywords: fabricPool, best practices, encryption, compressions, tiering, AFF, consistency 
summary: 'Quando si configura un sistema StorageGRID per l"utilizzo con FabricPool, evitare di impostare opzioni globali che potrebbero influire sul modo in cui i dati vengono salvati.' 
---
= Altre Best practice per StorageGRID e FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si configura un sistema StorageGRID per l'utilizzo con FabricPool, evitare di impostare opzioni globali che potrebbero influire sul modo in cui i dati vengono salvati.



== Crittografia degli oggetti

Durante la configurazione di StorageGRID, è possibile attivare l'impostazione globale *crittografia oggetto memorizzato* se è richiesta la crittografia dei dati per altri client StorageGRID (*CONFIGURAZIONE* > *sistema* > *Opzioni griglia*). I dati a più livelli da FabricPool a StorageGRID sono già crittografati, pertanto l'attivazione dell'impostazione StorageGRID non è necessaria. Le chiavi di crittografia lato client sono di proprietà di ONTAP.



== Compressione degli oggetti

Durante la configurazione di StorageGRID, non attivare l'impostazione globale *compress stored objects* (*CONFIGURATION* > *System* > *Grid options*). I dati a più livelli da FabricPool a StorageGRID sono già compressi. L'attivazione di *compress stored objects* non riduce ulteriormente la dimensione di un oggetto.



== Livello di coerenza

Per i bucket FabricPool, il livello di coerenza consigliato è *Read-after-new-write*, che è l'impostazione predefinita per un nuovo bucket. Non modificare i bucket FabricPool per utilizzare *Available* o qualsiasi altro livello di coerenza.



== Tiering FabricPool

Se il nodo StorageGRID utilizza lo storage assegnato da un sistema NetApp ONTAP, verificare che il volume non disponga di un criterio di tiering FabricPool attivato. Ad esempio, se un nodo StorageGRID è in esecuzione su un host VMware, assicurarsi che il volume che esegue il backup del datastore per il nodo StorageGRID non abbia un criterio di tiering FabricPool attivato. La disattivazione del tiering FabricPool per i volumi utilizzati con i nodi StorageGRID semplifica la risoluzione dei problemi e le operazioni di storage.


IMPORTANT: Non utilizzare mai FabricPool per eseguire il tiering dei dati relativi a StorageGRID su StorageGRID. Il tiering dei dati StorageGRID su StorageGRID aumenta la risoluzione dei problemi e la complessità operativa.
