---
permalink: fabricpool/using-storagegrid-ilm-with-fabricpool-data.html 
sidebar: sidebar 
keywords: FabricPool, requirements, ILM, information lifecycle management, ILM rule, ILM rules, ILM policy, erasure-coding, replication, cloud storage pool, glacier 
summary: Se si utilizza FabricPool per eseguire il tiering dei dati in StorageGRID, è necessario comprendere i requisiti per la creazione di regole di gestione del ciclo di vita delle informazioni StorageGRID e una policy ILM per la gestione dei dati FabricPool. È necessario garantire che le regole ILM applicabili ai dati FabricPool non siano disgreganti. 
---
= Utilizza la gestione del ciclo di vita delle informazioni di StorageGRID con i dati FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si utilizza FabricPool per eseguire il tiering dei dati in StorageGRID, è necessario comprendere i requisiti per la creazione di regole ILM (Information Lifecycle Management) di StorageGRID e una policy ILM per la gestione dei dati FabricPool. È necessario garantire che le regole ILM applicabili ai dati FabricPool non siano disgreganti.


IMPORTANT: FabricPool non conosce le regole o le policy ILM di StorageGRID. La perdita di dati può verificarsi se il criterio ILM di StorageGRID non è configurato correttamente. Vedere xref:../ilm/index.adoc[Gestire gli oggetti con ILM] Per istruzioni ILM dettagliate.

Consulta queste linee guida per assicurarti che le tue regole ILM e le policy ILM siano adatte ai dati FabricPool e ai tuoi requisiti di business. Se si utilizza già ILM di StorageGRID, potrebbe essere necessario aggiornare il criterio ILM attivo per soddisfare queste linee guida.

* Puoi utilizzare qualsiasi combinazione di regole di replica e erasure coding per proteggere i dati del livello cloud.
+
La Best practice consigliata consiste nell'utilizzare la codifica di cancellazione 2+1 all'interno di un sito per una protezione dei dati conveniente. L'erasure coding utilizza più CPU, ma offre una capacità di storage significativamente inferiore rispetto alla replica. Gli schemi 4+1 e 6+1 utilizzano una capacità inferiore rispetto allo schema 2+1. Tuttavia, gli schemi 4+1 e 6+1 sono meno flessibili se è necessario aggiungere nodi di storage durante l'espansione della griglia. Per ulteriori informazioni, vedere xref:../expand/adding-storage-capacity-for-erasure-coded-objects.adoc[Aggiungere capacità di storage per gli oggetti con codifica per la cancellazione].

* Ogni regola applicata ai dati FabricPool deve utilizzare la codifica di cancellazione oppure creare almeno due copie replicate.
+

IMPORTANT: Una regola ILM che crea una sola copia replicata per qualsiasi periodo di tempo mette i dati a rischio di perdita permanente. Se esiste una sola copia replicata di un oggetto, quest'ultimo viene perso in caso di errore o errore significativo di un nodo di storage. Inoltre, durante le procedure di manutenzione, ad esempio gli aggiornamenti, si perde temporaneamente l'accesso all'oggetto.

* Non utilizzare una regola ILM che scadrà o eliminerà i dati del livello cloud di FabricPool. Impostare il periodo di conservazione in ogni regola ILM su "Perforever" per garantire che gli oggetti FabricPool non vengano eliminati da ILM StorageGRID.
* Non creare regole che spostino i dati del Tier cloud FabricPool dal bucket a un'altra posizione. Non è possibile utilizzare le regole ILM per archiviare i dati FabricPool su nastro utilizzando un nodo di archiviazione o utilizzare un pool di storage cloud per spostare i dati FabricPool in un altro archivio di oggetti.
+

NOTE: L'utilizzo dei pool di storage cloud con FabricPool non è supportato a causa della latenza aggiunta per recuperare un oggetto dalla destinazione del pool di storage cloud.

* A partire da ONTAP 9.8, è possibile creare tag a oggetti per semplificare la classificazione e l'ordinamento dei dati a più livelli. Ad esempio, è possibile impostare i tag solo sui volumi FabricPool collegati a StorageGRID. Quindi, quando si creano le regole ILM in StorageGRID, è possibile utilizzare il filtro avanzato tag oggetto per selezionare e inserire questi dati.




== Esempio di policy ILM per i dati FabricPool

Utilizza questo semplice esempio di policy come punto di partenza per le tue regole e policy ILM.

In questo esempio si presuppone che si stiano progettando le regole ILM e una policy ILM per un sistema StorageGRID con quattro nodi di storage in un singolo data center a Denver, Colorado. I dati FabricPool in questo esempio utilizzano un bucket denominato `fabricpool-bucket`.


CAUTION: Le seguenti regole e policy ILM sono solo esempi. Esistono diversi modi per configurare le regole ILM. Prima di attivare una nuova policy, simulare la policy proposta per confermare che funzionerà come previsto per proteggere il contenuto dalla perdita. Per ulteriori informazioni, vedere xref:../ilm/index.adoc[Gestire gli oggetti con ILM].

.Fasi
. Creare un pool di storage denominato *DEN*. Selezionare il sito di Denver.
. Creare un profilo di codifica Erasure denominato *2 più 1*. Selezionare lo schema di erasure coding 2+1 e il pool di storage *DEN*.
. Creare una regola ILM che si applica solo ai dati in `fabricpool-bucket`. Questa regola di esempio consente di creare copie codificate per la cancellazione.
+
[cols="1a,2a"]
|===
| Definizione della regola | Valore di esempio 


 a| 
Nome regola
 a| 
2 più 1 erasure coding per i dati FabricPool



 a| 
Nome bucket
 a| 
`fabricpool-bucket`

È anche possibile filtrare l'account tenant FabricPool.



 a| 
Filtraggio avanzato
 a| 
Dimensione oggetto (MB) maggiore di 0.2 MB.

*Nota:* FabricPool scrive solo oggetti da 4 MB, ma è necessario aggiungere un filtro dimensione oggetto perché questa regola utilizza la codifica di cancellazione.



 a| 
Tempo di riferimento
 a| 
Tempo di acquisizione



 a| 
Posizionamento
 a| 
Dal giorno 0 memorizzare per sempre



 a| 
Tipo
 a| 
Codifica di cancellazione



 a| 
Posizione
 a| 
DEN (2 più 1)



 a| 
Comportamento di acquisizione
 a| 
Bilanciato

|===
. Creare una regola ILM che creerà due copie replicate di qualsiasi oggetto non corrispondente alla prima regola. Non selezionare un filtro di base (account tenant o nome bucket) o filtri avanzati.
+
[cols="1a,2a"]
|===
| Definizione della regola | Valore di esempio 


 a| 
Nome regola
 a| 
Due copie replicate



 a| 
Nome bucket
 a| 
_nessuno_



 a| 
Filtraggio avanzato
 a| 
_nessuno_



 a| 
Tempo di riferimento
 a| 
Tempo di acquisizione



 a| 
Posizionamento
 a| 
Dal giorno 0 memorizzare per sempre



 a| 
Tipo
 a| 
Replicato



 a| 
Posizione
 a| 
DEN



 a| 
Copie
 a| 
2



 a| 
Comportamento di acquisizione
 a| 
Bilanciato

|===
. Creare una policy ILM proposta e selezionare le due regole. Poiché la regola di replica non utilizza alcun filtro, può essere l'ultima regola predefinita per il criterio.
. Acquisire oggetti di test nella griglia.
. Simulare il criterio con gli oggetti di test per verificare il comportamento.
. Attivare il criterio.


Quando questo criterio è attivato, StorageGRID inserisce i dati degli oggetti come segue:

* I dati a più livelli di FabricPool in `fabricpool-bucket` verrà eseguito un erasure coding utilizzando lo schema di erasure coding 2+1. Due frammenti di dati e un frammento di parità verranno posizionati su tre diversi nodi di storage.
* Tutti gli oggetti in tutti gli altri bucket verranno replicati. Verranno create due copie e collocate su due diversi nodi di storage.
* Le copie replicate e codificate in cancellazione verranno conservate in StorageGRID fino a quando non verranno eliminate dal client S3. StorageGRID ILM non eliminerà mai questi elementi.

